tklengyel/drakvuf

.travis.yml, configure.ac, src/file_extractor.c, src/injector.c, src/vmi.c, src/vmi.h, src/xen_helper.c
With Xen 4.6 now officially released, moving DRAKVUF to this new version will enable taking advantage of some of the newest features as well.
=> Migrate DRAKVUF to Xen 4.6

src/libdrakvuf/drakvuf.c, src/libdrakvuf/drakvuf.h, src/libdrakvuf/injector.c, src/libdrakvuf/private.h, src/libdrakvuf/vmi.c, src/plugins/filetracer/filetracer.c, src/plugins/syscalls/syscalls.c
This PR allows DRAKVUF to safely run on multi-vCPU guests using the Xen altp2m system. DRAKVUF creates two altp2m views so that when a breakpoint is hit, instead of having to remove it, we just switch to the default view with singlestepping enabled, and afterwards switch back the breakpointed view. This can be performed specific to each vCPU thus no race-condition exists during execution.
=> Use Xen altp2m to allow multi-vCPU tracing

src/libdrakvuf/Makefile.am, src/libdrakvuf/drakvuf.h, src/libdrakvuf/win-processes.c
I updated the `filedelete` plugin to use the new API. Please test this carefully as I didn't manage to get `filedelete` to work properly in the `master` branch so I couldn't really test the modifications comprehensively. 
This is the output in case of 64-bit guest:
```
Volatility Foundation Volatility Framework 2.5
No suitable address space mapping found
Tried to open image as:
MachOAddressSpace: mac: need base
LimeAddressSpace: lime: need base
WindowsHiberFileSpace32: No base Address Space
WindowsCrashDumpSpace64BitMap: No base Address Space
WindowsCrashDumpSpace64: No base Address Space
HPAKAddressSpace: No base Address Space
VirtualBoxCoreDumpElf64: No base Address Space
VMWareMetaAddressSpace: No base Address Space
VMWareAddressSpace: No base Address Space
QemuCoreDumpElf: No base …
```
=> Created drakvuf_get_current_process API in libdrakvuf

src/libdrakvuf/win-processes.c
1. Fix using uninitialized-variables on certain functions that lead to unpredictable values: The enums are of 32bits size by default (compiler implementation dependant but at least on gcc and clang++ it is) but some functions treat them as 8bits so if the original variable is not initialized the final value will be unpredictable
2. Fix walking the processes list on drakvuf_find_eprocess(): The variable 'current_process' was not properly updated
=> Fix errors on win-process.c

src/libdrakvuf/vmi.c
Also, sanitizing shutdown routine to avoid crashing when bailing out on failed inits. Should fix segfault reported in #125.
=> Create all tables in init_vmi to avoid unclean shutdown

src/libdrakvuf/drakvuf.c, src/libdrakvuf/libdrakvuf.h
`bool drakvuf_get_module_base_addr( drakvuf_t drakvuf, addr_t *module_list_head, const char *module_name, addr_t *base_addr_out )`
This PR replaces #99
=> Added new routine for getting module base address

src/libdrakvuf/vmi.c
Apparently altp2m view destroy doesn't actually free the tables in Xen, just deactivates them. On subsequent creation of the altp2m tables, the same remappings are active as before. So, if we do two DRAKVUF runs with different plugins, we might end up getting the following errors:
`Ignoring old breakpoint event found in the queue`
This error comes from the re-activated remappings of old DRAKVUF traps that now have no subscribers. By reverting all remappings on shutdown we can avoid running into this issue.
=> Revert remapping on shutdown in idx view

configure.ac, src/drakvuf.cpp, src/drakvuf.h, src/libdrakvuf/Makefile.am, src/libdrakvuf/drakvuf.c, src/libdrakvuf/libdrakvuf.h, src/libdrakvuf/private.h, src/libdrakvuf/vmi.c, src/libdrakvuf/vmi.h, src/libdrakvuf/win-exports.c, src/libdrakvuf/win-exports.h, src/libdrakvuf/win-handles.c, src/libdrakvuf/win-processes.c, src/libinjector/Makefile.am, src/libinjector/injector.c, src/libinjector/libinjector.h, src/libinjector/private.h, src/main.cpp
Relocate injector codebase from libdrakvuf to its own separate library and convert all traps to use DRAKVUF traps instead of manual LibVMI traps. On x86 Windows use new method of trapping userspace entry as the APC injection method is unreliable on multi-vCPU guests.
Fixes #148
=> Libinjector

src/drakvuf.cpp, src/injector.c, src/libdrakvuf/drakvuf.c, src/libdrakvuf/private.h, src/libdrakvuf/vmi.c, src/libinjector/injector.c, src/xen_helper/xen_helper.c, src/xen_helper/xen_helper.h
The pause/unpause pairs have been out of whack since vmi_pause_vm no longer increments Xen's pause count. This resulted in the VM getting unpaused after every add_trap call.
=> Pause tweaking

src/libdrakvuf/vmi.c
PR #194 attempted to fix the permissions on pages when injecting a breakpoint to an already monitored page for executions. However, the permissions were merged for the remapped page instead of the current_gfn. The remapped_gfn should not actually be accessible with it's real gfn in the default view at all.
=> Merge access rights on the right page

src/dirwatch/dirwatch.c
`gotlock` might be undefined when reaching line 215 otherwise
=> Initialize gotlock in dirwatch.c

src/plugins/syscalls/syscalls.cpp
This will ensure that macros such as `PRIu32` etc. will be defined correctly, as `config.h` will define `__STDC_FORMAT_MACROS` if necessary
=> Include config.h from syscalls.cpp

src/libdrakvuf/vmi.c
If writing with the `vmi_write_pa` call has succeded return value will be VMI_SUCCESS
=> Fix vmi_write_pa return value

src/libdrakvuf/private.h
clang complains:
`
vmi.c:768:39: error: taking address of packed member 'guard' of class or structure 'breakpoint' may result in an unaligned pointer value [-Werror,-Waddress-of-packed-member]
remove_trap(drakvuf, &container->breakpoint.guard);
^~~~~~~~~~~~~~~~~~~~~~~~~~~`
=> Don't pack internal structures

src/plugins/filetracer/filetracer.cpp
Variable file_name_us has already been NULL-checked.
=> Fix Coverity CID 188773

src/plugins/cpuidmon/cpuidmon.cpp, src/plugins/debugmon/debugmon.cpp, src/plugins/exmon/exmon.cpp, src/plugins/exmon/private.h, src/plugins/filedelete/filedelete.cpp, src/plugins/filetracer/filetracer.cpp, src/plugins/objmon/objmon.cpp, src/plugins/plugins.h, src/plugins/poolmon/poolmon.cpp, src/plugins/regmon/regmon.cpp, src/plugins/socketmon/socketmon.cpp, src/plugins/ssdtmon/ssdtmon.cpp, src/plugins/syscalls/syscalls.cpp
Adds timestamps to logging statements so me can relate DRAKVUF-generated events with external ones (e.g., output from other tools).
=> Log current time in seconds and microseconds.

src/plugins/procmon/procmon.cpp
CommandLine and ImagePathName is UNICODE_STRING, not PUNICODE_STRING.
=> PROCMON: Fix CommandLine and ImagePathName extracting

src/libdrakvuf/libdrakvuf.h, src/libinjector/injector.c, src/main.cpp, src/plugins/cpuidmon/cpuidmon.cpp, src/plugins/debugmon/debugmon.cpp, src/plugins/exmon/exmon.cpp, src/plugins/exmon/private.h, src/plugins/filedelete/filedelete.cpp, src/plugins/filetracer/filetracer.cpp, src/plugins/objmon/objmon.cpp, src/plugins/poolmon/poolmon.cpp, src/plugins/procmon/procmon.cpp, src/plugins/regmon/regmon.cpp, src/plugins/socketmon/socketmon.cpp, src/plugins/ssdtmon/ssdtmon.cpp, src/plugins/syscalls/syscalls.cpp
Existing output formats does not automatic parser friendly.
Default format is multi-line. The CSV format is inconvenient for writing parsing rules.
=> Added KeyValue output format

tools/rekall_linux_profile_fix.sh
Rekall generates profiles for kernels 4.13+ with `task_struct` missing elements. Running this script on the profile will fix-it up. 
Script originally from @mbushou in https://github.com/google/rekall/issues/337
=> Add script to fix-up Linux Rekall profiles

src/libdrakvuf/drakvuf.c, src/libdrakvuf/libdrakvuf.h, src/libdrakvuf/private.h, src/libdrakvuf/vmi.c, src/libdrakvuf/vmi.h, src/xen_helper/xen_helper.c, src/xen_helper/xen_helper.h
WIP for plugin-defined event sources:
DRAKVUF plugins allow users to build upon the core DRAKVUF framework.  Recently, I was experimenting with a use case that, in addition to consuming normal guest events, needed to also receive messages from an external event source via a ZMQ socket.  This could be used to programmatically send a DRAKVUF plugin a message to change its behavior at runtime and could allow DRAKVUF to be more easily integrated into larger security systems.  This work in progress solution might be useful to others and I wanted offer it for upstream consideration.  
This WIP allows plugins to register their own external file-descriptor-based event sources into DRAKVUF's event loop.  A plugin registers one or more file descriptors (FDs) with DRAKVUF and DRAKVUF monitors these …
=> API for additional FD-based event sources

configure.ac
On occasion compilation fails with `fatal error: 'set' file not found` or `fatal error: 'cassert' file not found`. This is due to clang++ not finding the stdc++ library, so manually specifying `--with-stdlib=libc++` works around the problem.
=> Add option to specify C++ stdlib

src/drakvuf.cpp, src/drakvuf.h, src/libdrakvuf/libdrakvuf.h, src/libdrakvuf/os.c, src/libdrakvuf/os.h, src/libdrakvuf/win-exports.c, src/libdrakvuf/win-exports.h, src/libdrakvuf/win.c, src/plugins/Makefile.am, src/plugins/filedelete/filedelete.cpp, src/plugins/filedelete/filedelete.h, src/plugins/filedelete/filedelete2.cpp, src/plugins/filedelete/private.h, src/plugins/plugins.h
Hello.
This a work in progress to make filedelete plugin capable to catch the whole file contents of modified or deleted files.
Current status:
- Content fetching is based on function injection on NtClose.
- File modification catching is based on trapping NtWriteFile (ZwCreateSection in future).
Known issues:
~~Sometimes files not catched.~~
Advanced research needed for `STATUS_PENDING` and `STATUS_INVALID_DEVICE_REQUEST`
~~Adwanced applications use NtCreateSection/NtMapViewOfSection for writing into files.~~
Advanced research needed to handle `STATUS_PENDING`. Seems like file handle could be closed after section handle obtaining.
=> Plugin Filedelete | Catch whole file contents on NtClose (Part 1)

src/plugins/filedelete/filedelete.cpp, src/plugins/filedelete/filedelete2.cpp
Some applications use sections and views to read/write files.
Add handles of files for which section with `SECTION_MAP_WRITE` flag have been
created into registry of changed files.
Filter out system handles. Those having mask `0xffffffff80000000`.
=> Plugins | Filedelete | Add hook to `ZwCreateSection()'

src/libdrakvuf/drakvuf.c, src/libdrakvuf/libdrakvuf.h, src/libdrakvuf/private.h, src/libdrakvuf/vmi.c, src/libdrakvuf/vmi.h, src/xen_helper/xen_helper.c, src/xen_helper/xen_helper.h
PR #405 introduced severe CPU overhead due to the changes of how polling for events is performed. Reverting it for now until the reason for the overhead is better understood.
/cc @mbushou
=> Reverse #405, CPU overhead issue

.travis.yml
This allows all users to enable checking of their branches before
creating Pull Requests.
To enable Coverity Scan one should create COVERITY_SCAN_TOKEN
and other variables in Travis CI project's settings.
-----
@tklengyel I have changed `.travis.yml` so it could not pass Coverity test. You should define all variables in your Travis CI project's settings.
=> Replace hardcoded Coverity token with Travis CI variable

.travis.yml, sonar-project.properties
One should define SONAR_TOKEN variable in Travis CI project's settings.
-----
@tklengyel this patch defines new test in `.travis.yml` which requires a project named *drakvuf* on [SonarCloud](https://sonarcloud.io). You could see my [example](https://sonarcloud.io/project/issues?id=skvl-drakvuf&resolved=false&severities=BLOCKER&types=CODE_SMELL) project.
=> Add Travis CI addon for SonarQube

src/plugins/filedelete/filedelete.cpp, src/plugins/procmon/procmon.cpp, src/plugins/socketmon/socketmon.cpp
The EPROCESS address from the process that triggered the trap can be obtained just using the `proc_data` info instead of calling (again) the `drakvuf_get_current_process()` function from inside the plugin.
=> Remove drakvuf_get_current_process() call from plugins

src/drakvuf.cpp, src/drakvuf.h, src/injector.c, src/libdrakvuf/libdrakvuf.h, src/libdrakvuf/linux-processes.c, src/libdrakvuf/linux.h, src/libdrakvuf/os.c, src/libdrakvuf/os.h, src/libdrakvuf/private.h, src/libdrakvuf/win-processes.c, src/libdrakvuf/win.h, src/libinjector/injector.c, src/libinjector/libinjector.h, src/main.cpp, src/plugins/socketmon/socketmon.cpp
PR #471 identified a race-condition in which a multi-vCPU guest can start executing the injected process before returning to the trapped userspace address. This is problematic because events of interest can be missed while the process executes as the plugins haven't yet started. In this PR we continue listening to CR3 events in injector and if the injected process is detected to be running, the loop is broken and `start_app` returns. To allow the trapped userspace stack to be fixed-up a final cleanup needs to be called.
=> Listen on CR3 event during injection to catch new process

src/plugins/filedelete/filedelete.cpp
The array is heap allocated and not guaranteed to be page aligned.
This addresses Issue #467.
=> filedelete: fix bogus alignment check on _SUBSECTION's _MMPTEs

src/libdrakvuf/win-exports.c
Fix some memory leaks when using unicode strings in `win-exports.c`, these leaks are located inside a loop so IMHO are of enough importance.
=> Remove memory leaks in win-exports

src/plugins/filedelete/filedelete.cpp, src/plugins/filedelete/private.h, src/plugins/regmon/regmon.cpp
It looks like this (for kv output):
> filedelete Time=1544205779.986203,PID=2980,PPID=1612,ProcessName="\Device\HarddiskVolume2\Program Files (x86)\Mozilla Firefox\firefox.exe",Method=ReadFile ret,FileName="",Size=8759,FO_FLAGS=0x40042(FO_SYNCHRONOUS_IO | FO_CACHE_SUPPORTED | FO_HANDLE_CREATED)
Note new `Size` and `FO_FLAGS` fields.
=> Filedelete: print file size and _FILE_OBJECT.Flags

src/plugins/filedelete/filedelete.cpp
I have missed type conversion while moving up function `is_synchronous`.
=> FILEDELETE: fix segfault

src/plugins/filedelete/filedelete.cpp, src/plugins/filedelete/filedelete2_helpers.cpp
Without this in log one could see `ReadFile ret` instead of `NtSetInformationFile`.
=> Filedelete: save original breakpoint name while injecting

src/drakvuf.cpp, src/drakvuf.h, src/injector.c, src/libinjector/Makefile.am, src/libinjector/injector.c, src/libinjector/injector_stack.c, src/libinjector/libinjector.h, src/libinjector/private.h, src/main.cpp
* Move setup_stack functionality into separate file
* Add support for injection via ShellExecute on x86 arch
* Remove -w command line argument (always wait for first execution of injected process before initializing plugins)
* Remove unused structure definitions and unused structure fields from
injector code.
This PR implements injection algorithm from #474:
1. Call CreateProcess with CREATE_SUSPENDED flag; 
2. Store PID of created suspended process;
3. Install cr3_callback for waiting of first occurence of PID;
4. Call ResumeThread to wake up process;
5. Freeze VM on first occurence of PID;
6. Initialize plugins;
7. Do looping.
=> * Inject program via creation of suspended process and resuming it

src/plugins/filedelete/filedelete.cpp, src/plugins/filedelete/private.h
Sometimes `NtReadFile` returns `STATUS_INVALID_DEVICE_REQUEST` for some reason. In that case the `.mm` file is only saved without `.metadata`.
Also I have found that I've forgotten (or somehow removed) to check for `STATUS_END_OF_FILE`.
=> FILEDELETE: save metadata for partially read files

src/drakvuf.cpp, src/injector.c, src/libdrakvuf/libdrakvuf.h, src/libinjector/injector.c, src/plugins/bsodmon/bsodmon.cpp
* Enable parsing more easy with `Status=%STATUS%` strings
* Move error handling from `drakvuf.cpp` into `libinjector/injector.c`
=> Print injection status in linbinjector

src/libdrakvuf/win-processes.c
Fix error:
```
win-processes.c: In function ‘win_is_ethread’:
win-processes.c:380:41: error: enum conversion in initialization is invalid in C++ [-Werror=c++-compat]
dispatcher_object_t dispatcher_type=0;
^
win-processes.c: In function ‘win_is_eprocess’:
win-processes.c:405:41: error: enum conversion in initialization is invalid in C++ [-Werror=c++-compat]
dispatcher_object_t dispatcher_type=0;
^
cc1: all warnings being treated as errors
=> Initialize enum with defined value

.gitmodules
Installing rekall from pip3 has issues running due to dependency errors. Install rekall manually instead from the git repository.
=> (re-)Add Rekall submodule

src/dirwatch/dirwatch.c, src/dirwatch/distributor.c, src/drakvuf.cpp, src/libdrakvuf/drakvuf.c, src/libdrakvuf/rekall-profile.c, src/libdrakvuf/vmi.c, src/libdrakvuf/win-exports.c, src/libdrakvuf/win-handles.c, src/libdrakvuf/win-processes.c, src/libdrakvuf/win.c, src/main.cpp, src/plugins/exmon/exmon.cpp, src/plugins/filedelete/filedelete.cpp, src/plugins/filedelete/filedelete.h, src/plugins/poolmon/poolmon.cpp, src/plugins/socketmon/socketmon.cpp, src/plugins/ssdtmon/ssdtmon.cpp, src/plugins/syscalls/syscalls.cpp, src/xen_helper/xen_helper.c, src/xen_memclone.c
Init-declarator-lists and member-declarator-lists should consist of single init-declarators and member-declarators respectively for c and c++.
=> Define each identifier in a dedicated statement

src/libdrakvuf/drakvuf.c, src/libdrakvuf/libdrakvuf.h, src/libdrakvuf/linux-processes.c, src/libdrakvuf/linux.c, src/libdrakvuf/linux.h, src/libdrakvuf/os.c, src/libdrakvuf/os.h, src/libdrakvuf/private.h, src/libdrakvuf/win-processes.c, src/libdrakvuf/win.c, src/libdrakvuf/win.h, src/plugins/socketmon/socketmon.cpp
* Add missing PID and PPID info for socket owner (need for strong
process identification).
* Deduplicate code for some callbacks in socketmon.
* Add missing TcpState fields in JSON output format.
* Rename LocalIp, LocalPort -> ListenIp, ListenPort for listening
sockets in KV and JSON output formats.
=> SOCKETMON: Add PID and PPID info for socket owner process.

src/libdrakvuf/win-processes.c
Before the patch search for WoW64 modules under x86 OS result in segmentation fault in drakvuf.
=> Fix error in WoW64 modules search for x86 OS

src/main.cpp
-  Created an option `-a` to activate the specified plugin and disabling the rest.
- It disables all the plugins only once 
- `-a` can be used to activate multiple plugins
Usage: `./src/drakvuf -r /root/windows7-sp1.rekall.json -d 1 -a poolmon -a syscalls` 
This activates only the specified plugins.
- Code formatting of file is done.
=> Added option '-a' to activate the specified  plugin

src/plugins/dkommon/dkommon.cpp, src/plugins/dkommon/dkommon.h
Such writes have been used in the past in CVEs like CVE-2014-4113.
=> dkommon: Monitor writes to zero page

src/plugins/filetracer/win_acl.cpp
This prevents endless loops and out-of-bound reads.
=> Check for bad ACEs while parsing ACLs

configure.ac, src/main.cpp, src/plugins/Makefile.am, src/plugins/memdump/memdump.cpp, src/plugins/memdump/memdump.h, src/plugins/plugins.cpp
Implements a new Windows plugin called `memdump` which reacts when somebody calls `NtFreeVirtualMemory` on something that looks like a binary - very simple heuristic based on presence of `MZ` magic in the first two bytes of the memory block. A memory dump is stored to the location pointed by `--memdump-dir`.
Exemplary sample for which this works:
`423d8a075a52a44ae43287d48ec46fa60eb9b7da15a163627bb3e7a8e1f67b43`
Note: it also exhibits some interesting behavior of crashing the whole VM and this is probably by design.
For this particular one, a UPXed binary is dumped which could be then decompressed using `upx -d`. The resulting file contains unpacked code of the malware which is easy to analyze statically.
**Note about dump file name:** Exemplary dump name `1752-0x1e10000-0001.dmp` meets …
=> Implement basic memory dumping plugin

src/libdrakvuf/rekall-profile.c
Som rekall profiles from https://github.com/google/rekall-profiles have a `ProfileClass` that contains only `Nt`.
You can `gunzip -d` the first one from this list to confirm (`0018A9A7F0334E8D965F310D1653A5452.gz`):
https://github.com/google/rekall-profiles/tree/gh-pages/v1.0/nt/GUID
=> rekall: fix rekall_get_os_type when ProfileClass value is just "Nt"

src/plugins/procmon/procmon.cpp
This PR fixes the JSON output of `protect_virtual_memory_hook_cb`
=> procmon: produce valid JSON in NtProtectVirtualMemory callback

src/libdrakvuf/libdrakvuf.h, src/libdrakvuf/os.c, src/libdrakvuf/os.h, src/libdrakvuf/win-processes.c, src/libdrakvuf/win.c, src/libdrakvuf/win.h, src/plugins/memdump/memdump.cpp, src/plugins/memdump/memdump.h, src/plugins/procmon/procmon.cpp, src/plugins/procmon/procmon.h
Integrated @alexmocha code from PR #655 into `memdump` plugin.
In case of `NtWriteVirtualMemory` it is very important to log some non-standard parameters like target process PID (to whom the write was done) and target base address. Thus, `dump_memory_region` now accepts `printout_extras` callback, which is capable of adding some syscall-specific things to the printouts.
=> Extend memdump plugin: track NtWriteVirtualMemory (integrate alexmocha's code)

src/libdrakvuf/rekall-profile.c
`[src/libdrakvuf/rekall-profile.c:406]: (error) Width 15 given in format string (no. 6) is larger than destination buffer 'junk[15]', use %14s to prevent overflowing it.`
=> Fix cppcheck warning

src/main.cpp, src/plugins/Makefile.am, src/plugins/memdump/memdump.cpp, src/plugins/memdump/memdump.h, src/plugins/memdump/userhook.cpp, src/plugins/plugins.cpp, src/plugins/plugins.h, src/plugins/plugins_ex.h, src/plugins/procmon/procmon.cpp, src/plugins/wmimon/wmimon.cpp
The aim of this PR is to implement robust, runtime user mode hooking and to eliminate (at least some) problems discussed in #669.
What we do:
* we hook on `NtMapViewOfSection` and `NtProtectVirtualMemory`, because these system calls are specific to the Windows loader, so we could observe a DLL being loaded by the process
* if the DLL seems to be interesting, we make sure that `IMAGE_EXPORT_DIRECTORY` is fully readable, if not then we use `vmi_request_page_fault` to force Windows to map these memory pages
* we compute the addresses of interesting functions using `vmi_translate_sym2v` and make sure if the corresponding pages are readable, if not then we also cause a page fault
Sometimes, a page fault may trigger a system service exception. For that reason we hook `KiSystemServiceException` …
=> memdump: Dumps based on user mode API calls

src/libdrakvuf/vmi.c
At the moment, there is no clear way to enable `altp2m` when Xen is wrapped by libvirt/virsh. This PR adds an additional check which is executed when DRAKVUF inits and so invalid altp2m configuration is automatically corrected.
=> Enable altp2m in runtime when DRAKVUF starts

src/libdrakvuf/vmi.c, src/xen_helper/xen_helper.c, src/xen_helper/xen_helper.h
Fix some travis errors with sonarcloud
```
vmi.c:1458:25: error: use of undeclared identifier 'XEN_ALTP2M_external'
if (param_altp2m != XEN_ALTP2M_external)
=> Move altp2m enabling to xen_helper 

src/libdrakvuf/drakvuf.c, src/libdrakvuf/libdrakvuf.h, src/libdrakvuf/os.c, src/libdrakvuf/os.h, src/libdrakvuf/win-processes.c, src/libdrakvuf/win.c, src/libdrakvuf/win.h, src/plugins/Makefile.am, src/plugins/memdump/memdump.cpp, src/plugins/memdump/memdump.h, src/plugins/memdump/private.h, src/plugins/memdump/stack_util.cpp, src/plugins/memdump/userhook.cpp
When process does an interesting syscall, walks the usermode stack to get some information about the cause. Dumps the offending code fragments if they appear to be interesting.
=> memdump: Dumps based on stack inspection

src/plugins/memdump/memdump.cpp
Add previously-forgotten check. The heuristic is to track the situation when malware injects its code to the other process.
=> memdump: Fix heuristic for write-memory dumps, don't dump self-writes

src/libinjector/injector.c
Currently, with `-o json` injector outputs log lines in default format, which may be inconvenient. This PR adds JSON output format.
=> Add JSON output mode in injector

src/plugins/memdump/private.h, src/plugins/memdump/userhook.cpp
As hooks are added per physical address, any write access to the page with the hook causes loss of it due to copy on write. This PR hooks MiCopyOnWrite function and re-adds hooks after moving hooked function to another physical address.
=> memdump: CoW hooks

src/plugins/memdump/userhook.cpp
If there were failed hooks, "trap" was NULL causing crashes.
=> fix HOOK_FAIL lookup in CoW

src/libdrakvuf/win-processes.c, src/plugins/memdump/memdump.cpp, src/plugins/memdump/stack_util.cpp
[Work in progress] Fix `memdump` so it doesn't require WOW64 NTDLL profile to be provided at all times.
=> memdump: initialize properly even if WOW64 NTDLL profile is not provided

src/plugins/Makefile.am
This PR removes useless CPP flags, since the C++ compiler will always show warnings for missing prototypes.
source: https://stackoverflow.com/a/2389184/3017219
=> build: remove Wstrict-prototypes and Wmissing-prototypes for cpp

src/libdrakvuf/vmi.c
Removing the entry completely is safe for both remapped and non-remapped GFNs as it will just trigger a copy form the hostp2m on the next fault.
This is most likely the bug behind the following tickets:
Fixes #576 
Fixes #622 
Thanks to @icedevml for finally figuring this one out!
=> Fix lingering remapped gfns after memaccess traps are gone

.travis.yml
There was a release pushed without any artifacts o_O
https://github.com/tklengyel/drakvuf-builds/releases/tag/20191010175202-7b97fae
mostly because I've made a typo previously.
=> Fix artifacts in Travis-CI

src/libdrakvuf/vmi.c
As far as I understand right now:
1. This activates remapped gfns if the trap is added for the first time: https://github.com/CERT-Polska/drakvuf/blob/master/src/libdrakvuf/vmi.c#L1060
2. This sets mappings back to "normal" once trap is removed: https://github.com/CERT-Polska/drakvuf/blob/master/src/libdrakvuf/vmi.c#L822
3. If the trap is added once again, remapped gfns are not reactivated because `remapped_gfn->active` is still set to `1` and nowhere it is set to zero?
I have no idea what would be the exact impact of the proposed patch, but intuitively seems to solve the above issue?
/cc @sasza8
=> Fix bug with remapped_gfn not reactivating in breakpoint

package/postinst
Fix the drakvuf-bundle package complaining about missing EPT support when the system is already running on Xen during installation.
=> Fix warning about EPT not supported while already running on Xen

src/plugins/filetracer/filetracer.cpp
Comma before first key in `SecurityDescriptor` dict is making JSON unparseable.
=> [filetracer] Fix syntax error in JSON output (SecurityDescriptor)

src/libdrakvuf/vmi.c, src/libdrakvuf/win-processes.c, src/libinjector/win_injector.c, src/plugins/bsodmon/bsodmon.cpp, src/plugins/delaymon/delaymon.cpp, src/plugins/exmon/exmon.cpp, src/plugins/filedelete/filedelete.cpp, src/plugins/objmon/objmon.cpp, src/plugins/poolmon/poolmon.cpp, src/plugins/socketmon/socketmon.cpp, src/plugins/syscalls/syscalls.cpp
Examine breakpoint location to ensure that no instructions preceding it
can leak the breakpoint during execution. Certain instructions can fetch
subsequent memory and store it in registers, thus potentially revealing
the presence of the breakpoint. This is due to the fetch being performed
as part of the instruction and thus no read-access is performed.
This is an extra hardening step against code that may try to detect the
presence of DRAKVUF. When it is deemed unsafe to use the breakpoint
instruction itself, DRAKVUF reverts to a fallback mode using
memory permission based monitor and simulated int3 events. This backup
mode is a bit slower then using actual breakpoints but otherwise should
work without any sideeffect or the libdrakvuf caller having to know
where and when it is safe to use …
=> Harden breakpoints against instruction injection leaks

src/plugins/memdump/memdump.cpp, src/plugins/memdump/private.h
There are some unsafe values of `ptr_length` that could potentially lead to buffer overflow in `inspect_stack_ptr`. We replace `ptr_length` with `bool is_32bit` parameter, so method caller doesn't have the possibility to cause overflow.
=> [memdump] Fix possible buffer overflow

package/build.sh, package/mkdeb
More robust package version detection && possibility to specify it manually if it's not detected (happens in some environments).
=> Package build: allow to specify version manually

package/mkdeb
Move `deb/DEBIAN/conffiles` generation to the proper place, so all files belonging to `/etc` are captured there.
This fixes problem of DPKG overriding configuration files on package upgrade.
=> Fix conffiles in package build

src/plugins/filedelete/filedelete.cpp, src/plugins/filedelete/filedelete2_helpers.cpp
1. Fix duplicated file artifacts
start_readfile function reports error if (PID, TID, Handle) is
processed already. After that the fall-back method is called to download
the file.
2. Fix BSOD on multi-processing systems
BSOD occur if guest OS reschedule thread during ZwReadFile injection
cycle. This happens because before injection starts all registers are
saved. After read file finish all registers are restored. If OS reschedule
the thread to other vCPU then some system registers could be malformed
(e.g. GS BASE).
=> Fix several errors in filedelete plugin

src/main.cpp, src/plugins/plugins.cpp, src/plugins/plugins.h, src/plugins/wmimon/private.h, src/plugins/wmimon/wmimon.cpp, src/plugins/wmimon/wmimon.h
Starting from Windows 8 the CoCreateInstance functions resides in combase.dll.
The WoW is an exception.
Read WMI vtables based on OS arch
=> plugins/wmimon: use correct dll to find CoCreateInstance

.travis.yml, src/plugins/filetracer/filetracer.cpp, src/plugins/filetracer/filetracer.h
Valgrind caught a memory leak of trap if system exists before the callback has been issued for the dynamically allocated trap.
=> Filetracer: keep track of dynamically allocated traps

configure.ac, src/libdrakvuf/Makefile.am, src/libdrakvuf/private.h, src/libusermode/Makefile.am, src/libusermode/uh-private.hpp, src/libusermode/userhook.cpp, src/libusermode/userhook.hpp, src/plugins/memdump/memdump.h, src/plugins/memdump/userhook.cpp, tools/demangle.py
Move usermode hooking framework from `memdump` plugin to core DRAKVUF.
resolve #787
=> memdump: refactor usermode hooking into core DRAKVUF

src/libdrakvuf/Makefile.am, src/libdrakvuf/json-util.c, src/libdrakvuf/json-util.h, src/plugins/filedelete/filedelete.cpp, src/plugins/memdump/memdump.cpp
Store JSON metadata together with files dumped by `filedelete` plugin and memory dumps created by `memdump`. Add some util to make JSON-C usage easier.
resolve #779
=> memdump/filedelete: change metadata format to JSON

src/plugins/procmon/winnt.cpp
Left-shifting signed `1` more then 31-bits is undefined behavior.
=> Use VMI_GET_BIT in procmon

src/plugins/apimon/apimon.cpp, src/plugins/dkommon/dkommon.cpp, src/plugins/filedelete/filedelete.cpp, src/plugins/filetracer/filetracer.cpp, src/plugins/procmon/procmon.cpp, src/plugins/regmon/regmon.cpp, src/plugins/syscalls/syscalls.cpp
* Fix syntax errors when outputting `OUTPUT_JSON` from `apimon` plugin
* Introduce `TID` in printouts of some plugins
=> fix OUTPUT_JSON for various plugins

src/plugins/procmon/procmon.cpp
Normally, ProcMon tries to read the commandline information of the new created Process as "Unicode" via the "CommandLine" address from OS JSON Profile.
_EPROCESS->_PEB->ProcessParameters(_RTL_USER_PROCESS_PARAMETERS)->CommandLine
addr_t cmdline_addr = user_process_parameters_addr + f->command_line;
uses this way
However, in the OS JSON Profile file, CommandLine looks like a single field.
Normally, ProcMon does not have a problem and prints the CommandLine information, but if the CommandLine of the Process is long data, ProcMon cannot read and process it.(related to libvmi)
An error related to this was reported
#821
CommandLine(_UNICODE_STRING) has 3 fields on Windows systems.
0xAAAAA0    Length                          [unsigned short:Length]: 0x1882
0xAAAAA2    MaximumLength …
=> fix for ProcMon CommandLine Parse Problem

src/drakvuf.cpp, src/drakvuf.h, src/injector.c, src/libdrakvuf/drakvuf.c, src/libdrakvuf/libdrakvuf.h, src/libdrakvuf/private.h, src/libdrakvuf/vmi.c, src/main.cpp, src/proc_stat.cpp
In some situations, LibVMI doesn't always detect KPGD value in robust way. If somebody is operating in conditions where KPGD is well-known (e.g. DRAKVUF is continously being ran against VM with the same snapshot), the value may manually forced using `-k <kpgd value>` switch.
=> add -k switch that allows to provide KPGD value manually

src/plugins/syscalls/linux.cpp, src/plugins/syscalls/linux.h, src/plugins/syscalls/private.h, src/plugins/syscalls/syscalls.cpp, src/plugins/syscalls/win.cpp, src/plugins/syscalls/win.h
The previous single-array setup required a 17-sized arg array to be allocated for each syscall, which was just a waste of memory. With a bit of macro-magic we just create a separate struct for each syscall & have a syscall argument struct for each, then collect their pointers into an array.
=> Store syscall definitions in custom structs

src/plugins/apimon/apimon.cpp, src/plugins/apimon/crypto.cpp
Use vmi_lock_guard in apimon/crypto.cpp.
Fix memory leak in apimon/crypto.cpp.
=> Fix memory leak in apimon/crypto.cpp

src/Makefile.am, src/librepl/Makefile.am, src/librepl/repl.cpp
This PR adds all functions from libdrakvuf to librepl. This allows to pretty much do anything using REPL. I've also prepared a [usage guide](https://github.com/CERT-Polska/drakvuf/wiki/REPL-introduction-guide), which could be added to wiki.
Since ctypes expect a `.so` library to call functions and libdrakvuf doesn't build into .so I decided to be clever and compile `repl` binary with PIE and expose all functions, so that ctypes load repl binary just like `.so`.
This PR also adds ability to change `event_response`, which in theory allows to modify registers (not tested yet).
=> add libdrakvuf functions to REPL

src/plugins/syscalls/syscalls.cpp
ProcessName, Module, Method had incorrect output from new changes. Dangling comma left in sysret args.
Before:
```
{"Type" : "syscall","TimeStamp" :"1585851942.406507","VCPU": 0,"CR3": 730857474,"ProcessName": "NtCancelTimer","UserName": SessionID,"UserId": 1"PID" : 876,"PPID": 504,"TID": 900,"Module": "(null)","Method": "(null)","Args": ["Args": [{"TimerHandle" :516},{"CurrentState" :0}] }
{"Type" : "sysret","TimeStamp" :"1585851942.406567","VCPU": 0,"CR3": 730857474,"ProcessName": "NtCancelTimer","UserName": SessionID,"UserId": 1"PID" : 876,"PPID": 504,"TID": 900,"Module": "nt","Method": "(null)","Args": ["Ret": 0,"Info": "STATUS_SUCCESS",] }
{"Type" : "syscall","TimeStamp" :"1585851942.406624","VCPU": 0,"CR3": 730857474,"ProcessName": "NtQueryInformationThread","UserName": …
```
=> fix bug in syscalls output

src/drakvuf.cpp, src/drakvuf.h, src/libinjector/injector.c, src/libinjector/libinjector.h, src/libinjector/linux_injector.c, src/libinjector/private.h, src/libinjector/win_injector.c, src/main.cpp, src/plugins/filedelete/filedelete.cpp, src/plugins/memdump/memdump.cpp
Sometimes drakvuf fails to inject because of invalid sample (e.g. x64 sample
for x86 VM). This allows to distinguish such situations.
=> libinjector: return injection status

configure.ac, package/mkdeb
For nightly Debian packages published with `drakvuf-releases`, the current version scheme is `0.7-<commit_hash>`. Having two debs with version `0.7` it's not possible to tell which one is more recent.
This PR changes the version scheme to: `0.7+git<year><month><day><hour><minute><second>+<git_short_hash>-1`. With such format (I hope) Debian will be able to understand which package is older and which is the upgraded version.
Example: `0.7+git20200425213254+ec3a0e7-1`
=> drakvuf-releases: make versions sortable

src/plugins/syscalls/syscalls.cpp
JSON output broke again. In some spare time I'll rewrite this to json-c.
=> syscalls: fix OUTPUT_JSON syntax errors

package/extra/etc/default/grub.d/xen.cfg, package/extra/usr/bin/drak-find-xen-defaults, package/mkdeb
Currently we ship xen.cfg with fixed 2048 MB / 4 CPU allocation for Dom0. This PR changes this behavior so half of the system resources will be dedicated to Dom0 and this could be manually overriden.
This is not extremely optimal, but I hope it's a user-friendly default. Something would work with these settings (better or worse) and then the user has the possibility to fine-tune.
=> drakvuf-bundle: Automatically propose Xen Dom0 settings

package/Dockerfile-xen, package/build.sh, package/mkdeb
* `sh package/build.sh` can now have optional argument of a build base image, e.g. `sh package/build.sh ubuntu:20.04`, default is `ubuntu:18.04` (which produces package compatible with both Debian Buster and Ubuntu 18.04)
* implement patches required for Xen to compile/work under Ubuntu 20.04
=> Adjust package build process for Ubuntu 20.04

src/plugins/syscalls/linux.cpp
From official g_hash_table_lookup () documentation:
...Note that this function cannot distinguish
between a key that is not present and one which
is present and has the value NULL.
=> Fix linux syscalls filter functionality.

package/Dockerfile-final
The debug printouts will not show by default but would have to be enabled with:
* `LIBVMI_DEBUG=1` for LibVMI
* `-v` switch for DRAKVUF
this would make it much easier to diagnose some bugs.
=> Enable optional debug output for drakvuf-bundle

package/build.sh
I always forget to uncomment this:
```
```
let's just make a special exception in the code for Travis
=> Fix package build error in Travis

src/plugins/Makefile.am, src/plugins/envmon/envmon.cpp, src/plugins/output_format.h, src/plugins/output_format/common.h, src/plugins/output_format/csvfmt.h, src/plugins/output_format/deffmt.h, src/plugins/output_format/jsonfmt.h, src/plugins/output_format/kvfmt.h, src/plugins/output_format/ostream.cpp, src/plugins/output_format/ostream.h, src/plugins/output_format/xfmt.h, src/plugins/type_traits_helpers.h
I have tried to unify various printers.
So it can print only 'fmt' defined types and types should be specified in print() explicitly.
=> added version 2 of type-safe printers + envmon with it

src/plugins/procdump/private.h, src/plugins/procdump/procdump.cpp, src/plugins/procdump/procdump.h
* Fix parsing of prototype PTEs while traversing VAD. This fixes dumping memory-mapped files (at the time DLLs).
* Split dumping processes into two stages: stage 1 hooks NtTerminateProcess to dump all non-memory-mapped files regions and stage 2 hooks MmCleanProcessAddressSpace to dump memory-mapped files regions. This would allow to dump more information in the feature (at least I belive so).
=> Procdump update

package/build.sh, src/plugins/memdump/memdump.cpp
Added create_remote_thread_hook_cb to memdump plugin. It should help dumping malware unpacked using classic dll and reflective dll injection techniques which both rely on CreateRemoteThread procedure.
=> Added create_remote_thread_hook_cb in memdump plugin.

src/plugins/syscalls/private.h, src/plugins/syscalls/win.cpp
The logic of the current code cannot obtain the correct return value in some cases. For example:  Use the parameter **-S** (syscalls filter) to set a monitor on **NtFunctionA** . When this monitored function called, it will trigger **syscall_cb** and get the return address from the stack pointed to by the **rsp** register, and add a trap at that address. But this **NtFunctionA** will call other functions which will reach the same return address of this **NtFunctionA.** Based on the logical of the current code, it will remove this return trap. And we will see the return value of another function. So, just use the **tid** is not enough, i use the **rsp** value to resolve this problem for windows system calls. I don't know if this completely solved the problem, Sorry.
Because I am not …
=> Fix windows syscalls error: capture unreliable return values

src/libusermode/userhook.cpp, src/libusermode/userhook.hpp, src/plugins/apimon/apimon.cpp, src/plugins/memdump/userhook.cpp
Introduce new kind of apimon log line when `OUTPUT_JSON` is used:
```json
{
"Plugin": "apimon",
"Event": "dll_loaded",
"Rva": {
"SetupDiGetClassDevsA": 39104,
"SetupDiGetClassDevsW": 20292,
"SetupDiGetDeviceRegistryPropertyA": 417636,
"SetupDiGetDeviceRegistryPropertyW": 23640,
"SetupDiBuildDriverInfoList": 71040,
"IsUserAdmin": 720196
},
"DllBase": "0x7fefdf70000",
"DllName": "\\Windows\\System32\\setupapi.dll",
"PID": 1424
}
```
this gives a lot of hints about where the DLLs are in particular processes.
=> apimon: log DLL ImageBase and function RVAs when hooking

package/Dockerfile-xen, package/depends.sh, package/swab.patch
Linux headers are now fixed in Debian, no need to apply `swab.patch`
=> Remove swab.patch for Debian build

src/libdrakvuf/win-wow-offsets-map.h, src/libdrakvuf/win-wow-offsets.h, src/plugins/memdump/memdump.cpp, src/plugins/memdump/memdump.h, src/plugins/memdump/private.h
It seems that windows does not modify win32startaddress on NtSetContextThread call as I thought. Instead, now I hook on NtSetInformationThread and I retrieve both eax/eip registers from WOW64_CONTEXT structure. This covers two variants of process hollowing: when Eip is substituted (shellcode injection), and when entry point is changed by modifying eax register.
=> Changed ProcessHollowing heuristic. Hooking on NtSetInformationThread.

src/plugins/apimon/apimon.cpp, src/plugins/output_format/jsonfmt.h
Use `fmt::` for printing logs, fixing a small bug at the same time.
When trying to format empty `Extra` map, the code would erroneously print `,` thus breaking JSON.
=> apimon: use new fmt API for logging

src/plugins/output_format/jsonfmt.h
This is to keep parity between plugins that were already rewritten to the new output formatter and the old plugins which all output `TimeStamp`.
=> OUTPUT_JSON: rename Time key to TimeStamp to be backwards-compatible

src/libinjector/win_injector.c
For `-m writefile/readfile` the injection loop makes one unnecessary pass with the original RIP, which was occasionally causing crashes.
=> injector: fix bug in writefile/readfile injection method

src/libinjector/libinjector.h, src/libinjector/win_injector.c
fix some bugs in writefile method in injector, gracefully handle the situation when there was an error opening/writing/closing file
=> injector: fix bugs in writefile method

src/drakvuf.cpp, src/drakvuf.h, src/injector.c, src/libdrakvuf/drakvuf.c, src/libdrakvuf/libdrakvuf.h, src/libdrakvuf/vmi.c, src/libdrakvuf/vmi.h, src/main.cpp, src/proc_stat.cpp, src/repl.cpp
While using the new fast singlestep feature from Xen 4.14 a bug has been popping up. When a previous run of DRAKVUF was stopped while fast singlestep was set but before the MTF trap occured, the fast singlestep setting remains in effect either though MTF itself gets disabled. Next time when a new run of DRAKVUF is started and the first event that triggers is an EPT event, the corresponding `post_mem_cb` is skipped since the fast singlestep setting is still set in Xen. There is currently no way to remove the fast singlestep setting. This is only an issue when multiple runs of DRAKVUF are done, with a single run this is not an issue so we keep the option available to use it. However, while the issue is fixed upstream we don't set it as the default.
=> Make fast singlestep optional

src/plugins/output_format/jsonfmt.h
Xval in JSON format should be represented as `"0x1234"`, not as a decimal. It's absolutely hard to manually read virtual addresses in decimal etc.
=> OUTPUT_JSON: print Xval as actual hex string, not as a number

src/libdrakvuf/vmi.c
resolve #960
Improve performance of DRAKVUF in some corner cases (e.g. co-existing BREAKPOINT traps and dynamic MEMACCESS X traps). This logic is belived to be stale and already covered by different mechanisms.
=> libdrakvuf: don't apply old_access flags on breakpoint guard trap

src/plugins/procmon/procmon.cpp
=> procmon: fix uninitialized members (from coverity)

src/libusermode/uh-private.hpp, src/libusermode/userhook.cpp, src/libusermode/userhook.hpp, src/plugins/apimon/apimon.cpp, src/plugins/memdump/userhook.cpp
This allows to provide a CLSID in dll hooks list which is used as meta information to link multiple events in output e.g.:
```
System32\taskschd.dll,ITaskService::GetFolder,clsid,0F87369F-A4E5-4CFC-BD3E-73E6154572DD,20520,log,this:lpvoid,path:bstr,ppFolder:lpvoid*
```
=> libusermode,apimon,memdump: print CLSID from dll hook list

src/plugins/procmon/winnt.cpp
The error was introduced in d158bf532867075037785eaf72d1657e1450b314
Split #975
=> procmon: fix logical error

src/plugins/output_format/kvfmt.h
The key value pair with empty quoted string should be printed.
The error was introduced in c2d8bbe8bfdcb6a5014e7a6cbf31088cd2b7b008
Split #975
=> kvfmt: fix format for quoted strings

configure.ac
AC_PROG_CXX sets `g++` as default if no `clang++` is found. We don't want that. Add minimal test program that bugs out on `g++` to stop configure from continuing. Once `g++` supports C++20 this will no longer be necessary.
=> Don't let configure continue with g++ if no clang++ is found

src/plugins/output_format/common.h
The SIGSEGV could occur with something like this `fmt::Qstr((const char*)0)`
The `Rstr` have been patched to be uniform with `Qstr`
=> output_format: fix segfault on nullptr string

src/libdrakvuf/drakvuf.c, src/libdrakvuf/libdrakvuf.h, src/libdrakvuf/private.h, src/libdrakvuf/vmi.c
Because for the IPT we need to inject a special PTWRITE packet whenever a DRAKVUF breakpoint is hit, the IPT plugin needs to have ability to subscribe to all breakpoints. It doesn't need any special insight about what other plugins do, but it needs such kind of event to properly synchronize the IPT logs.
This might look weird but I hope reasonable.
=> ipt: implement CATCHALL_BREAKPOINT trap type

configure.ac, src/xen_helper/Makefile.am, src/xen_helper/xen_helper.c, src/xen_helper/xen_helper.h
Can be enabled conditionally with `./configure --enable-ipt`, special Xen version required: https://github.com/icedevml/xen/commits/ipt-patch-v7d
Once vmtrace IPT is upstreamed, it could be compiled-in by default.
=> ipt: xen_helper: implement methods to support vmtrace IPT

src/libusermode/printers/printers.cpp, src/libusermode/printers/printers.hpp, src/libusermode/userhook.cpp, src/libusermode/userhook.hpp, src/main.cpp, src/plugins/apimon/apimon.cpp, src/plugins/apimon/apimon.h, src/plugins/memdump/memdump.h, src/plugins/memdump/userhook.cpp, src/plugins/plugins.cpp, src/plugins/plugins.h
This unifies the output of libusermode with other plugins where we print only values but no addresses
=> libusermode: stop print addresses of string arguments

src/libdrakvuf/libdrakvuf.h, src/libdrakvuf/private.h, src/libdrakvuf/vmi.c, src/plugins/output_format/jsonfmt.h
Assign an unique sequential ID to each trap occurrence. This number will be both printed in DRAKVUF's output (implemented by this PR) and injected into IPT logs in appropriate place (further PR will implement it). This will be used to synchronize DRAKVUF with Intel Processor Trace.
=> ipt: implement event counter

configure.ac, src/libusermode/printers/printers.hpp, src/plugins/Makefile.am, src/plugins/plugins.cpp, src/plugins/plugins.h, src/plugins/rpcmon/rpcmon.cpp, src/plugins/rpcmon/rpcmon.h
This plug-in allows to trace NdrXxx family of functions from `rpcrt4.dll`.
This on-going work. Though I would like to share is as soon as possible to avoid re-base conflicts in the future.
This branch depends on #999
=> rpcmon: add new plug-in

src/libdrakvuf/drakvuf.c
This condition
```cpp
if ( !drakvuf->catchall_breakpoint )
return 0;
```
was added by mistake and is causing that `CATCHALL_BREAKPOINT` can not be used.
=> Fix bug in CATCHALL_BREAKPOINT creation

src/plugins/apimon/apimon.cpp
Use std::map instead of std::vector as printing data causes
unnecessary array ([]) to be created in JSON output.
=> apimon: Fix "Extra" data output formatting

src/plugins/procdump/procdump.cpp
The error has been introduced in bd35d25f1cd95270588417d99d05220775451c17.
The `skip` variable is useless here but makes static checkers happy. The
main purpose here is changing the value of `ptes_to_dump`.
=> procdump: fix endless loop for Windows 10

src/plugins/plugins_ex.h
Note: I'm not so sure if this is correct fix as I'm not to familiar with this part of code.
When trying to add a usermode hook on return from function I've encountered an error in `register_trap`. It turned out that when running 32 bit sample, the `breakpoint_by_dtb_searcher` was reading 8 bytes from stack instead of expected 4 bytes (pointer width for 32 bit applications). Same issue occurs in `breakpoint_by_pid_searcher`.
=> Check for wow64 in breakpoint searchers

src/plugins/filedelete/filedelete.cpp
When the key is removed from the map, iterator becomes invalid,
later access becomes use-after-free.
Fix the issue by hoisting the variable to outer scope.
=> filedelete: Fix use-after-free in close_cb

src/plugins/regmon/regmon.cpp
Casting pointers with reinterpret_cast in some cases might violate
alignment requirements. Use memcpy to fix this issue.
=> regmon: Use memcpy instead of reinterpret_cast

src/libusermode/printers/printers.cpp
Sometimes `apimon` encounters an invalid string or just a byte buffer. When it tries to print it as ASCII/Unicode string, invalid characters might appear in JSON. Here we try to escape all non-printable characters with backslash sequences, to avoid producing binary output out of DRAKVUF.
/cc @BonusPlay @chivay @kscieslinski 
/cc @skvl (you might be affected by this change)
related https://github.com/CERT-Polska/drakvuf-sandbox/issues/270
=> argument printers: escape non-printable characters in strings

package/extra/etc/default/grub.d/xen.cfg
Turns out that scripts in `/etc/default/grub.d` are running inside `/bin/dash` which works differently than bash o_O
Fix bug that was causing `update-grub` always saying that drakvuf-bundle is not installed.
=> drakvuf-bundle: fix bug in xen.cfg

src/drakvuf.cpp, src/libusermode/uh-private.hpp, src/libusermode/userhook.cpp, src/plugins/envmon/envmon.cpp, src/plugins/librarymon/librarymon.cpp, src/plugins/memdump/memdump.cpp, src/plugins/plugins_ex.cpp, src/plugins/plugins_ex.h, src/plugins/procdump/procdump.cpp, src/plugins/procmon/procmon.cpp, src/plugins/wmimon/wmimon.cpp
- remove allocators, as noone used them
- remove a lot of templates from hook params
- separate `get_trap_params` and `get_trap_plugin`
- use `std::unique_ptr` with custom deleter for traps
- minimal changes to old API
Currently WIP as this is 1st commit where "it builds", now it needs extended testing.
=> Refactor plugins_ex class

package/extra/etc/default/grub.d/xen.cfg
There are some scheduling issues with `sched=credit2` that are becoming especially visible when machine has many PCPUs. I've confirmed with Andrew Cooper that there were some reports about `credit2` recently.
I propose to default to `sched=credit` in drakvuf-bundle, which is a more stable choice.
=> drakvuf-bundle: default to sched=credit

src/libusermode/userhook.cpp, src/libusermode/userhook.hpp, src/plugins/apimon/apimon.cpp, src/plugins/memdump/userhook.cpp, src/plugins/rpcmon/rpcmon.cpp
In current implementation, log strategy is implemented as a std::string.
Using an enum is both faster and less error-prone.
Additionaly, remove the concept of "stack" strategy as it has no sense
(doing work, without any benefit to the user).
=> libusermode: refactor log strategies

src/drakvuf.cpp, src/injector.c, src/libinjector/injector.c, src/libinjector/libinjector.h, src/libinjector/private.h, src/libinjector/win_injector.c
Add `-w` command line switch in `injector` which blocks until the termination of injected program is observed. Program's exit code is captured and `injector` returns error if it's non-zero.
=> injector: optionally wait until injected process terminates

.github/workflows/deb.yml, .travis.yml
Switch from Travis to GitHub Action, it builds much much faster and we could also build for 3 distros in parallel.
* When somebody makes a pull request, a dry run of package build is executed (release creation and asset upload steps are skipped).
* When the PR is pushed to master, actual release is created and assets are uploaded.
=> Build Debian packages using GitHub Actions

src/plugins/output_format/csvfmt.h, src/plugins/output_format/deffmt.h, src/plugins/output_format/jsonfmt.h, src/plugins/output_format/kvfmt.h, src/plugins/output_format/xfmt.h, src/plugins/procmon/procmon.cpp
In all plugins KV format uses "Time" field for timestamp.
=> Fix KV-format of RunningProcess messages

src/libusermode/running.cpp, src/libusermode/uh-private.hpp, src/libusermode/userhook.cpp, src/libusermode/userhook.hpp, src/plugins/apimon/apimon.cpp, src/plugins/memdump/userhook.cpp, src/plugins/rpcmon/rpcmon.cpp
This is just a very small refactor of libuserhook. This pr. should fix memory leak issues observed in #1060
=> Small libuserhooks refactor. Make it a proper singleton.

src/libdrakvuf/libdrakvuf.h, src/libdrakvuf/linux.c, src/libdrakvuf/linux.h, src/libdrakvuf/os.c, src/libdrakvuf/os.h, src/libdrakvuf/win.c, src/libdrakvuf/win.h, src/libusermode/userhook.cpp, src/libusermode/userhook.hpp, src/plugins/apimon/apimon.cpp, src/plugins/filedelete/filedelete.cpp, src/plugins/filetracer/linux.cpp, src/plugins/filetracer/win.cpp, src/plugins/memdump/userhook.cpp, src/plugins/plugins_ex.h, src/plugins/procdump/procdump.cpp, src/plugins/procmon/procmon.cpp, src/plugins/rpcmon/rpcmon.cpp, src/plugins/syscalls/linux.cpp, src/plugins/syscalls/private.h, src/plugins/syscalls/win.cpp, src/plugins/wmimon/wmimon.cpp
This attempt is not ideal, but it takes a step towards unifying the checks that the breakpoint was triggered at the exit from the call we need.
=> Unify return callback checks

src/plugins/rpcmon/rpcmon.cpp
Intercept NdrClientCall3 and print InterfaceId and TransferSyntax extracted from it arguments.
=> rpcmon: Intercept NdrClientCall3

src/plugins/procdump/private.h, src/plugins/procdump/procdump.cpp
* add target_rsp checks on exit from injected calls
* extract inject_copy_memory function
* fix some memory skipping in case of injection error
=> fix: target_rsp checks in procmon plugin

src/plugins/filedelete/filedelete.cpp, src/plugins/filedelete/filedelete2_helpers.cpp, src/plugins/filedelete/private.h
* add target_rsp checks on exit from injected calls
* replace manual lock management by RAII
* restore RIP and PSP registers after injection
=> fix: add target_rsp checks into filedelete plugin

src/libinjector/injector_stack.c
The error affects libinjector, procdump, memdump and filedelete plugins.
More about stack alignment:
* [x64 stack usage](https://docs.microsoft.com/en-us/cpp/build/stack-usage?view=msvc-160#stack-allocation)
* [In-depth: Windows x64 ABI: Stack frames](https://www.gamasutra.com/view/news/178446/Indepth_Windows_x64_ABI_Stack_frames.php)
* [About the x64 stack Alignment](https://community.intel.com/t5/Intel-ISA-Extensions/About-the-x64-stack-Alignment/td-p/881085)
* [what is "stack alignment"?](https://stackoverflow.com/a/672482)
=> libinjector: fix x64 stack alignment (#1086)

src/libinjector/injector_stack.c
I read the docs from #1097 and found yet another stack alignment bug.
The parameter area always contains at least four entries,
even if the called function has fewer arguments.
This fact must be taken into account when aligning the stack.
=> fix(libinjector): fix x64 stack alignment for functions with 1 or 3 parameters

src/drakvuf.cpp, src/drakvuf.h, src/main.cpp, src/plugins/bsodmon/bsodmon.cpp, src/plugins/bsodmon/bsodmon.h, src/plugins/filedelete/filedelete.cpp, src/plugins/filedelete/filedelete.h, src/plugins/plugins.cpp, src/plugins/plugins.h, src/plugins/plugins_ex.h, src/plugins/procdump/procdump.cpp, src/plugins/procdump/procdump.h
This is an on-going work to add infrastructure to stop and destroy plug-ins.
For example this would allow to stop all plug-ins except procdump before starting termination loop. Thus termination loop would become more clean and simple.
=> Add infrastructure to stop plugins

src/plugins/output_format/csvfmt.h, src/plugins/output_format/deffmt.h, src/plugins/output_format/jsonfmt.h, src/plugins/output_format/kvfmt.h, src/plugins/output_format/ostream.h
- Add RAII class RestoreFlags for undoing changes in stream format flags
- Replace manual "0x" printing by std::showbase.
- Rework time_val printers
- Replase printing of "\n" + flush() by std::endl.
=> Refactor output format printers

src/plugins/filedelete/filedelete.cpp, src/plugins/filedelete/filedelete.h, src/plugins/filedelete/filedelete2_helpers.cpp, src/plugins/filedelete/private.h
Because of the error the Windows fails to delete the file.
=> filedelete: fix handle leak

src/plugins/memdump/memdump.cpp
From the `g_checksum_get_string ()` docs:
> The returned string is owned by the checksum and should not be modified or freed.
Fix the double-free introduced by 52e93e5841f1590007f8f6b895fc5743f1009557
=> memdump: Fix double free

src/libusermode/userhook.cpp, src/libusermode/userhook.hpp, src/plugins/apimon/apimon.cpp, src/plugins/apimon/apimon.h, src/plugins/memdump/memdump.h, src/plugins/memdump/userhook.cpp, src/plugins/rpcmon/rpcmon.cpp, src/plugins/rpcmon/rpcmon.h
* Filter dll hook rules while config loading
* Load wanted hooks into structure optimized for on_dll_discovered logic (search on dll names only)
* Remove code duplication in libusermode clients (dll_name calculation and memory management)
* Replace C strstr call by C++ string::find
=> libuserhook on_dll_discovered logic refactored

src/libinjector/win_injector.c
Use a pointer to a string instead of a struct to use
vmi_free_unicode_str helper.
CC @icedevml
=> injector/win: Don't leak expanded_target

src/libusermode/printers/printers.cpp
Compilation may fail depending on the version of C++ standard library:
```
printers/printers.cpp:116:23: error: implicit instantiation of undefined template 'std::__1::basic_stringstream<char, std::__1::
char_traits<char>, std::__1::allocator<char>>'
std::stringstream os;
^
/snap/zig/3072/lib/libcxx/include/iosfwd:139:32: note: template is declared here
class _LIBCPP_TEMPLATE_VIS basic_stringstream;
^
printers/printers.cpp:159:23: error: implicit instantiation of undefined template 'std::__1::basic_stringstream<char, std::__1::
char_traits<char>, std::__1::allocator<char>>'
std::stringstream stream;
^
/snap/zig/3072/lib/libcxx/include/iosfwd:139:32: note: template is declared here
class _LIBCPP_TEMPLATE_VIS basic_stringstream;
^
```
=> libusermode: Add missing include to printers

src/main.cpp
Fail when user tries to enable or disable plugin that doesn't exist.
=> Validate plugin names passed by user

src/xen_helper/xen_helper.c, src/xen_helper/xen_helper.h
- Reworked xen_helper to make it compile with the final interface that landed in Xen.
- Replaced `xc_vmtrace_enable` with `xc_vmtrace_reset_and_enable` to allow tracing VM multiple times.
- Added `xen_set/get_ipt_option` to control MSRs
I have some doubts about error codes returned by IPT-related functions. All of them return ints, however
the values are negated  - the convention is to return 0 in case of success and non-zero in case of failure.
Additionaly, @tklengyel said that he prefers returning bools instead, so I think that return values should also be changed.
CC @icedevml
=> xen_helper: Fix vmtrace interface

src/xen_helper/xen_helper.c
OK, I'm dumb. Doing this for each vCPU does bad(tm) things to the heap.
=> xen_helper: Fix broken IPT shutdown

src/libdrakvuf/vmi.c
Reading through the code I came across a typo in the activation of remapped GFNs
the second part of the activation, it is changing **REMAPPED_GFN->R to SINK_PAGE_GFN** on `drakvuf->altp2m_idx`
`vmi_slat_change_gfn( drakvuf->vmi, drakvuf->altp2m_idx, remapped_gfn->r, drakvuf->sink_page_gfn)`
and as I can see when the slat change was previously made through XEN API  instead of VMI , it was **drakvuf->altp2m_idr** not **idx** as I expected
```
xc_altp2m_change_gfn(drakvuf->xen->xc, drakvuf->domID,
drakvuf->altp2m_idr, remapped_gfn->r, drakvuf->zero_page_gfn);
```
=> Fixing typo in vmi_slat_change

package/Dockerfile-xen
Semantics of `make dist` has changed, now it doesn't build the whole toolstack and the `drakvuf-bundle` is broken since some time. It doesn't contain the required Xen toolstack binaries.
=> Fix missing Xen toolstack in drakvuf-bundle

src/plugins/Makefile.am, src/plugins/plugins.cpp
There is no such option as `-Wimplicit-fallthrough=n` and `-Wextra` already enables `-Wimplicit-fallthrough=3`. It evidently didn't catch the previous error. Adding a more explicit `throw -1` in case the default switch case is reached.
=> Proper catching of plugin start fall-through

src/libinjector/win_injector.c
* make a printout when there is a LibVMI initialization problem (currently there is an exit_code = 1 with empty output);
* report actual error codes to allow distinguish if the file doesn't exist, there is some a permission problem or different cause;
* properly handle problems with file open on the host side;
=> injector: improve logging and error handling

src/libdrakvuf/drakvuf.c
=> libdrakvuf: fix memory leak on WoW offsets

src/libdrakvuf/win-processes.c
`win_get_process_name` uses two different approaches to yield the process name, one of which is not reliable when it comes to lengthy process names `ImageFileName` as it is a char array limited to `0x0F` (number varies between kernel versions/builds), thus if the process name is longer it may return incomplete name. To solve this, I used string splitting on the full path and took the last token which points to the process name. 
The `vmi_read_str_va` is kept in the return as fallback option in case the other method fails.
=> Refactor win_get_process_name : ImageFileName length varies

src/libdrakvuf/drakvuf.c, src/libdrakvuf/private.h, src/libdrakvuf/vmi.c, src/libdrakvuf/vmi.h
For idrx guard3 and guard4 we shouldn't be using inject_trap_mem because there the assumption is that it can share space with traps requested by plugins. But the idrx view is only for internal use, so we reduce the complexity of the code by special casing handling of the idrx W trap.
Fixes #1195
=> Context based view fixes

src/libusermode/userhook.cpp
If `vmi_translate_sym2v` fails while traversing list of targets in `internal_perform_hooking` then cycle breaks and not all requested hooks are set.
=> libusermode: fix DLL target traverse error

.github/workflows/codeql.yml, .github/workflows/compile.yml, .github/workflows/container-compile.yml, .github/workflows/scan-build.yml, .gitmodules, configure.ac, src/libdrakvuf/drakvuf.c, src/libdrakvuf/libdrakvuf.h, src/main.cpp, src/plugins/Makefile.am, src/plugins/ipt/ipt.cpp, src/plugins/ipt/ipt.h, src/plugins/plugins.cpp, src/plugins/plugins.h
This is a stripped-down version of the original IPT plugin. Most of the complex code has been
moved to hyperbee / codemon. This is just the core that controls tracing and dumps acquired
data to local files.
Plugin enhances acquired data streams with PTWRITE packets that contain information about
current CR3, thread ID and DRAKVUF event IDs.
Using the plugin is quite simple, user has to provide a directory to store the traces and pass flags
to enable tracing interesting code (`--ipt-trace-os` / `--ipt-trace-user`).
Since this functionality depends on Xen 4.15 which is currently in RC stage, plugin is disabled by default.
This changes require newer LibVMI version which includes `vmtrace_pos` in vCPU registers.
I'm not sure if we want to bump LibVMI at the same time as adding new plugin but …
=> Intel PT plugin v2

src/plugins/codemon/codemon.cpp
At the moment codemon doesn't make any dumps because `setup_dump_context` is accessing the access_context_t union in a wrong way.
https://github.com/libvmi/libvmi/blob/582fc95d8c412148114e158c6f090e85f04f335d/libvmi/libvmi.h#L730-L735
=> codemon: fix bug with memory dumps

src/libusermode/uh-private.hpp, src/libusermode/userhook.cpp
Fixed a bug with removing usermode hooks from a process, which calls a termination of another process.
=> Fix libusermode trap removing on process termination

src/libdrakvuf/drakvuf.c, src/libdrakvuf/libdrakvuf.h, src/xen_helper/xen_helper.c, src/xen_helper/xen_helper.h
Dear Tamas,
I want to ask for incorporating this pull request to drakvuf. The changes were made in order to enable access to qemu's monitor interface by utilizing [human-monitor-commands][] via the function [`libxl_qemu_monitor_command(...)`][] of `<libxl.h>` , which can be accessed directly from drakvuf's core now, so that the aforementioned HMP-commands can be transferred to a specific Xen-guest by utilizing its [`xen_interface_t`][] and domID.
This addition might be useful for future plugins to interact with the guests. (It might be especially useful for performing HID simulation, which is the task I currently work on.)
If you want to test the code by yourself, you could use the following snippet:
``` C
const char* in = "info version"; 
char* out = NULL;
/* 
* The following code …
```
=> Add the ability to access qemu monitor from drakvuf's core

src/libdrakvuf/drakvuf.c, src/libdrakvuf/libdrakvuf.h
Dear Tamas, 
this patch exposes `drakvuf_t`'s member variable ` domID` by introducing a getter-function named `drakvuf_get_dom_id(...)` in `libdrakvuf.h`. The addition of this getter-function enables plugins to
retrieve the ID of the Xen guest of interest in a convenient way. 
Diverging from my initial statement to use libvmi's `vmi_get_vmid(...)` I decided to expose the domID directly in `libdrakvuf.h`, since this seems to me to be a cleaner way than calling `drakvuf_lock_and_get_vmi(..)` and releasing it  afterwards.
To accomplish exposing the domID, I decided to typedef `domid_t` inside `libdrakvuf.h`, which is originally typedef'ed inside `xen.h` but not exposed anywhere. If you think, the getter-function should return a plain uint16_t to omit this repeated typedef, please let me …
=> Add function to expose drakvuf_t's domID in libdrakvuf.h

src/libinjector/injector.c, src/libinjector/win_injector.c
libinjector: fix potential null pointer dereferences of injected_pid parameter
=> libinjector: fix potential null pointer dereferences

src/exitcodes.h, src/main.cpp
Add --write-file command line option to inject a file into the running VM by using INJECT_METHOD_WRITE_FILE libinjector method.
Can be used multiple times to copy multiple files.
Syntax: drakvuf --writefile [src] [dst]
Copying is done earlier than -m method injection so you can write file into the VM before injecting it with createproc or others
=> Drakvuf write-file option

.gitignore, configure.ac, package/depends.sh, snapcraft.yaml, src/helpers/hiddump/Makefile.am, src/helpers/hiddump/hiddump.c, src/helpers/hiddump/readme.org
Dear Tamas,
this PR adds a utility program named `hiddump` to the tools-directory. `hiddump` captures HID events and stores relative and normalized versions of those events in a file, which can then serve later as a template for sending HID events to an analysis guest. 
To record those events, the input subsystem of the Linux kernel is utilized. The `hiddump` reads `input_event`-structs from one or multiple event files under `/dev/input/`, which are continuosly polled during the recording period. The timing information, which is provided in the form of `timeval`-structs, is converted to a relative timestamp starting at the beginning of the recording. If the event houses coordinates, those are mapped to a value range, which qemu uses in its monitor protocol. Afterwards the events are …
=> Add `hiddump` - a utility to record HID events 

src/drakvuf.cpp
I've noticed that my plugin does not work at the end of the analysis and I I've found why.
So, `stop_plugins` returns 1 if some plugin is in `pending`  state but then it is inverted into 0 in `is_stopped` function.
Then function returns `rc == 0` as if all plugins have been stopped which is incorrect.
=> logical bug in is_stopped function

src/libinjector/injector_stack.c
there is no difference between `place_string_on_stack_64` and `place_string_on_linux_stack`
=> remove redundant function

src/libdrakvuf/win.c, src/main.cpp, src/plugins/objmon/objmon.cpp, src/plugins/objmon/objmon.h, src/plugins/plugins.cpp, src/plugins/plugins.h
* _objmon_ have been re-factored to use `pluginex` interface
* `NtDuplicateObject` hook been added to capture output HANDLE
* _drakvuf_ options been added to manipulate the _objmon_
=> Objmon refactoring

src/libusermode/uh-private.hpp, src/libusermode/userhook.cpp, src/plugins/plugins_ex.h, src/plugins/syscalls/linux.cpp, src/plugins/syscalls/private.h, src/plugins/syscalls/syscalls.cpp, src/plugins/syscalls/syscalls.h, src/plugins/syscalls/win.cpp
I have noticed occasional segmentation faults while traversing `int3` hooks due to jump into null page. The relative code is:
```c
GSList* loop = lists[i];
while (loop)
{
trap_info.trap = (drakvuf_trap_t*)loop->data;
rsp |= trap_info.trap->cb(drakvuf, &trap_info);
loop = loop->next;
}
```
In GDB I get context:
```gdb
(gdb) i r
rax            0xb06aef0        184987376
rbx            0x0      0
rcx            0x7ffeb589a870   140731944118384
rdx            0xb05f560        184939872
rsi            0x7ffeb589a918   140731944118552
rdi            0x1040e20        17042976
rbp            0x7ffeb589a9f0   0x7ffeb589a9f0
rsp            0x7ffeb589a8c0   0x7ffeb589a8c0
r8             0x6      6
r9             0x0      0
r10            0xb066fc0        184971200
r11            0x0      0
r12 …
```
=> libuserhook, syscalls: fix possible segmentation fault

src/libinjector/win_injector.c
In "inject" event ProcessName will always equal to empty string if injector->expanded_target is not set.
=> Fix ProcessName calculation in 'inject' event log

src/plugins/syscalls/win.cpp
This fixes debug messages while syscal initializing:
Trap added @ PA 0x2a41435 RPA 0xff002435 Page 10817 for (null).
=> Add syscall trap name in syscalls plugin.

src/plugins/hidsim/gui/vmi_win_gui_parser.cpp
Dear Tamas, 
this patch fixes the defects introduced by PR #1275.
The following issues were addressed, which Coverity identified:
- CID 354685: Fix unchecked return value in l. 800  in `retrieve_winstas_from_procs(...)`
- CID 354686: Fix resource leak in l. 243+ in `construct_wnd_container(...)`
I did not address CID 354683, since I think, that this is a false positive.
Thanks already in advance for reviewing and considering this PR.
Best regards
Jan
=> Fix defects introduced by #1275

.github/workflows/ci.yml
codeQL also needs to be run on master branch. This should fix that error introduced in https://github.com/tklengyel/drakvuf/pull/1293
only `codeQL` will be run when on master. `scan-build`, `compile` and `tarbuild` should be skipped
=> [ci] fix codeQL run on master branch

src/plugins/syscalls/syscalls.cpp
Remove garbage bits from output
=> syscalls: Print WIN32_PROTECTION_MASK as uint32

src/libinjector/injector_stack.c, src/libinjector/libinjector.h
This PR adds support for creating arrays so that arrays can be used for `setup_stack` arguments
=> add support for arrays in injector stack

src/plugins/hidsim/gui/vmi_win_gui_parser.cpp
Dear Tamas, 
this PR fixes memory leaks inside the function `retrieve_winstas_from_procs`, which where identified by @manorit2001 in the course of the CI tests connected to #1300. This patch ensures, that memory allocated in the b/m function will be freed on fails.
Best regards 
Jan
=> Fix memory leaks in retrieve_winstas_from_procs

src/plugins/rootkitmon/rootkitmon.cpp
The leak was due to missing `g_checksum_free` call.
Addressing https://github.com/tklengyel/drakvuf/issues/1329.
=> rootkitmon memoryleak fix

src/plugins/hidsim/hid_injection.cpp
Dear Tamas,
this patch fixes a defect which identified by Coverity as CID 361179. 
It addresses a potential dereference of a nullptr stemming from an unchecked return value in `get_display_dimensions(...)`.
Thanks already in advance for reviewing and considering this PR.
Best regards
Jan
=> Fix potential dereference of nullptr (CID 361179)

src/main.cpp, src/plugins/hidsim/gui_monitor.cpp, src/plugins/hidsim/hid_injection.cpp, src/plugins/hidsim/hid_injection.h, src/plugins/hidsim/hidsim.cpp, src/plugins/hidsim/hidsim.h, src/plugins/plugins.cpp, src/plugins/plugins.h
Dear Tamas, 
this patch enhances the `hidsim`-plugin by the ability to inject random clicks, which is often needed to pass the passive RTTs employed by evasive malware.  In order to activate this behavior, a new CLI switch named `--hid-random-clicks` is introduced, which can be used to toggle it on. 
Thanks already in advance for reviewing and considering this PR.
Best regards
Jan
=> Enhance random HID even simulation by the ability to inject random clicks

src/libinjector/linux/methods/linux_write_file.c, src/libinjector/win/methods/win_write_file.c, src/plugins/hidsim/hid_injection.cpp
There are places in libinjector and hidsim plugins when it would be good practice to check if fread made the deal successfully.
It accually can be useful on file read error on injection
=> Fix fread() error handling

src/drakvuf.cpp
Logical error. If _drakvuf_ would been stopped like `drakvuf_interrupt(drakvuf, 1)` then endless loop occur.
=> drakvuf: fix stop plug-ins

src/plugins/dkommon/dkommon.cpp, src/plugins/dkommon/dkommon.h
The plugin tries to detect null pointer dereference which only happens with virtual memory, but hooks null physical page where IVT for bios is located.
=> removed zero page write

configure.ac
Since DRAKVUF only distributes binaries and its build utilizes only intermediate libraries to be linked with the binary targets, we can disable one of the build types to reduce the build time
=> disable shared library builds by default

src/libdrakvuf/drakvuf.c, src/libdrakvuf/json-profile.c, src/libdrakvuf/json-profile.h, src/libdrakvuf/libdrakvuf.h, src/plugins/exmon/exmon.cpp
exmon: use drakvuf_get_kernel_struct_members_array_rva function instead of manual iteration
=> exmon: use drakvuf_get_kernel_struct_members_array_rva function

configure.ac, src/main.cpp, src/plugins/Makefile.am, src/plugins/callbackmon/README.md, src/plugins/callbackmon/callbackmon.cpp, src/plugins/callbackmon/callbackmon.h, src/plugins/plugins.cpp, src/plugins/plugins.h, src/plugins/rootkitmon/rootkitmon.cpp
Hello!
This is the new plugin that aims to find installed/removed/hooked callbacks in kernel. We've found that some rootkits directly modify underlying data structures with callbacks bypassing api hooks.
I've also added more informative output compared to rootkitmon.
`Module` : module name that contains callback function
`RVA` : address within the module
`ListName` : callback type
`Action` : removed/added/replaced
CC: @disaykin
=> new plugin callbackmon

src/plugins/filetracer/private.h, src/plugins/filetracer/win.cpp
The first printing was done implicitly inside the `objattr_read` call, the second time - explicitly in the `create_file_ret_cb` method
=> filetracer: Fix bug with double print on create_file

package/depends.sh
Compiling Xen without libgnutls leads to a semi-broken VNC,
and a cryptic error while creating a domain:
qemu-system-i386: -vnc 0.0.0.0:0,password=on,to=99: Cipher backend does not support DES algorithm
Fix this by adding libgnutls28-dev to the compilation environment.
See: https://bugs.gentoo.org/832494
=> deb: Add libgnutls28-dev to Xen build dependencies

src/drakvuf.cpp, src/drakvuf.h, src/injector.c, src/libdrakvuf/drakvuf.c, src/libdrakvuf/libdrakvuf.h, src/libdrakvuf/linux-processes.c, src/libdrakvuf/private.h, src/libdrakvuf/win-processes.c, src/main.cpp, src/proc_stat.cpp, src/repl.cpp, src/xtf.c
With the optimizations provided:
* The whole `EPROCESS` structure is read at once and then parsed for `PID`, `PPID`, process name and image file name address.
* The `UserID` filed is made optional.
The optimization allows to avoid multiple `vmi_read`'s.
It have been tested that marker event occur faster (about 15%) with this optimizations.
=> libdrakvuf: optimize get windows process data

src/plugins/syscalls/syscalls.cpp, src/plugins/syscalls/syscalls.h, src/plugins/syscalls/win.cpp
When we encounter a new syscall without an internal definition its not safe to pass `symbol->name` as `trap->name` as it gets freed. We really only ought to copy the new syscall name if no internal definition is found, and use the internal definition's name if it is found as its already statically allocated.
Why this bug only triggered for syscalls with no internal definitions is unclear, by the looks of it it should have affected all syscalls. Perhaps some compiler optimization happened to hide it?
Fixes #1398
=> Fix printing syscall name after it has been freed

src/main.cpp, src/plugins/plugins.cpp, src/plugins/plugins.h, src/plugins/procdump2/private2.h, src/plugins/procdump2/procdump2.cpp, src/plugins/procdump2/procdump2.h
Additional timeout is used to prevent BSODs on plug-in stop.
The BSOD occur because on stop signal the plug-in doesn't remove hooks but perform new injects to dump target process. Thus on global timeout the plug-in destructor is called and VM is leaved in broken state on last injection.
Also the code is changed to store metadata for partial dumps. And dump status is inserted into "procdump" event and metadata.
The other error fixed is end-less "PsSuspendProcess" injection loop. In some cases the target process is awaken. And the VM catch BSOD on several dozens of "PsSuspendProcess" injections. I don't know the reason of BSOD. Though I believe that the end-less loop should be fixed.
=> Procdump fix

configure.ac, src/plugins/Makefile.am, src/plugins/plugins.cpp, src/plugins/plugins.h, src/plugins/spraymon/spraymon.cpp, src/plugins/spraymon/spraymon.h
Hi! I've made a new plugin `spraymon`. It's purpose is to detect possible spray attempts using win32k graphic objects by checking counters inside [W32PROCESS](https://www.geoffchappell.com/studies/windows/km/win32k/structs/processinfo/index.htm) structure. Since this structure is not really documented, symbol information is available only for Windows 7 and Windows 10 (>=1607). 
Checks are made when W32PROCESS information is being deleted from EPROCESS and at the end of the analysis.
=> New plugin spraymon 

src/plugins/procdump2/private2.h, src/plugins/procdump2/procdump2.cpp, src/plugins/procdump2/procdump2.h
It have been noticed that `MmCopyVirtualAddress` fails if any page in requested range is inaccessible. Thus it have been fixed how we use this system call.
=> procdump: fix fragmented address spaces

src/plugins/procdump2/private2.h, src/plugins/procdump2/procdump2.cpp, src/plugins/procdump2/procdump2.h
The BSOD scenario:
* The target process returns from `PsSuspendProcess`.
* After few retries to re-suspend it we restore its state and it continues the `NtTerminateProcess`.
* At this time the working thread injected `MmCopyVirtualMemory`.
* `MmCopyVirtualMemory` locks pages with `MmProbeAndLockPages`.
* The `PROCESS_HAS_LOCKED_PAGES` or `UNEXPECTED_KERNEL_MODE_TRAP` occur.
The fix delays execution of `NtTerminateProcess` with `KeDelayExecutionThread` until `MmCopyVirtualMemory` finishes.
=> procdump: fix BSOD on re-suspend fail

src/plugins/filetracer/win_acl.cpp
The KV output format been broken on empty `mask` field. E.g.:
```
filetracer Time=1648457161.131638,PID=1564,PPID=608,TID=5760,ProcessName="\Device\HarddiskVolume2\Windows\servicing\TrustedInstaller.exe",Method=NtCreateFile,FileName="\??\C:\Windows\Logs\CBS\CBS.log",FileHandle=0x11C,OBJ_CASE_INSENSITIVE=1,SE_DACL_PRESENT=1,Dacl=4,Type="ACCESS_ALLOWED_ACE_TYPE",DELETE=1,READ_CONTROL=1,WRITE_DAC=1,WRITE_OWNER=1,SYNCHRONIZE=1,STANDARD_RIGHTS_ALL=1,GENERIC_WRITE=1,GENERIC_READ=1,SID="S-1-5-32-544",Type="ACCESS_ALLOWED_ACE_TYPE",DELETE=1,READ_CONTROL=1,WRITE_DAC=1,WRITE_OWNER=1,SYNCHRONIZE=1,STANDARD_RIGHTS_ALL=1,GENERIC_WRITE=1,GENERIC_READ=1,SID="S-1-5
-18",Type="ACCESS_ALLOWED_ACE_TYPE",DELETE=1,SYNCHRONIZE=1,GENERIC_WRITE=1,GENERIC_READ=1,SID="Local …
```
=> filetracer: fix KV output format for empty mask

src/plugins/procdump2/procdump2.cpp
The error occur due to state switch before `if`. This results in not removable tasks in list in rare cases. Thus plug-in could not stop in timeout provided via `--procdump-timeout` option.
=> procdump: fix logical error on state switch

src/main.cpp
Because we terminate the process to observe its behavior during termination.
=> Terminate sample process if requested before stopping plugins

src/plugins/filedelete/filedelete.cpp, src/plugins/filedelete/filedelete2_helpers.cpp, src/plugins/filedelete/private.h, src/plugins/filetracer/linux.cpp, src/plugins/filetracer/private.h, src/plugins/filetracer/win.cpp, src/plugins/filetracer/win_acl.cpp, src/plugins/procmon/linux.cpp, src/plugins/procmon/private.h, src/plugins/syscalls/linux.cpp, src/plugins/syscalls/linux.h, src/plugins/syscalls/private.h, src/plugins/syscalls/syscalls.cpp, src/plugins/syscalls/win.cpp, src/plugins/syscalls/win.h
Do not use structures with the same name in different translation units.
This results in undefined behavior because the linker mistakenly merges
them into a single symbol.
As a result, we can get the following error in runtime:
free(): invalid pointer
=> plugins: add namespaces for private structures

src/plugins/filetracer/linux.cpp, src/plugins/output_format/common.h, src/plugins/output_format/csvfmt.h, src/plugins/output_format/deffmt.h, src/plugins/output_format/jsonfmt.h, src/plugins/output_format/kvfmt.h
* fix double escaping of FileName value in JSON; and
* fix incorrect formatting of FileName value in KV.
=> linux-filetracer: Fix some issues on FileName formatting

src/libinjector/win/methods/win_createproc.c, src/libinjector/win/methods/win_read_file.c, src/libinjector/win/methods/win_shellcode.c, src/libinjector/win/methods/win_shellexec.c, src/libinjector/win/methods/win_terminate.c, src/libinjector/win/methods/win_write_file.c
libinjector, win: Fix intermittent timeouts
After restoring the saved CPU registers, each injection method waits
for the next trap before exiting the injector loop. This means that
the target thread, continuing to execute the original program, needs
to trigger the same trap before the injector can finish. And that leads
to unpredictable waits. For example, waits of a few minutes were
observed when testing injector against explorer.exe under Windows 7
Enterprise (x64). Further, injector could wait forever in case the
target thread never revisits the trap.
The waits were introduced when refactoring injection methods in commit
3fdb3704de7c ("win_injector: seperate readfile and writefile to
different files  (#1319)").
Fix this issue by arranging for the injector loop to exit immediately
after …
=> Fix libinjector timeouts

src/libdrakvuf/linux-processes.c
The `task_struct` for Linux kernel threads contains null pointer (https://stackoverflow.com/a/25956682 , https://qr.ae/pvFGw3 ).
This results in errors like this:
```
1654086286.801804 Can't get exe_file from mm_struct
```
Thus we get empty names in some cases.
With the patch we set special name `kthread-PID`. This makes drakvuf output more clean.
=> libdrakvuf: print special names for kernel threads t

src/libinjector/injector_utils.c, src/libinjector/injector_utils.h, src/libinjector/win/methods/win_write_file.c
In case of empty file writing, state machine has been in wrong step STEP5, because of falling through STEP6 without incrementing the step.
=> windows-injector: handle case of writing empty file

src/libusermode/userhook.cpp, src/libusermode/userhook.hpp
Simplifies rules for use in `apimon` while DLL name comparison:
* Allow simple wildcard patter `*.dll`.
* Performs case insensitive search.
=> libusermode: DLL search case insensitive, simple wildcard pattern

src/plugins/syscalls/syscalls.cpp
JSON output breaks on '\r' in value:
"pathname": "/tmp/malware_drop.sh^M"
=> linux-syscalls: Fix JSON format escaping

src/plugins/fileextractor/fileextractor.cpp, src/plugins/fileextractor/fileextractor.h
Actually, the plugin didn't work, because created return_hook was immediately destroyed.
=> fileextractor: fix return_hook creation

src/libhook/hooks/return.hpp, src/plugins/fileextractor/fileextractor.cpp, src/plugins/plugins_ex.h
- make unlimited ttl for return hooks by default
- automaticaly save result call params
=> Improve createReturnHook

src/plugins/syscalls/syscalls.cpp, src/plugins/syscalls/syscalls.h, src/plugins/syscalls/win.cpp
support for early initialization (before launching of explorer.exe and loading of win32k.sys driver)
=> win-syscalls: support for early initialization

src/libinjector/injector_stack.c, src/libinjector/libinjector.h, src/libinjector/linux/linux_syscalls.c
The error was in the code for building of @argv and @envp arrays for execve system call:
int execve(char *const argv[], char *const envp[]);
The @argv and @envp arrays must each include a null pointer at the end of the array.
Instead of adding null pointer to the end of arrays, the pointer to memory with
8 zero bytes was placed.
=> linux-injector: fix execve arguments placing bug

src/libdrakvuf/drakvuf.c
This was part of my hunt for use-after-free bug.
The idea to assigning NULL to freed resources was given to me as a good practice some time ago.
=> Assign NULL to freed resources

src/libdrakvuf/drakvuf.c
From GLib docs:
Calling g_rec_mutex_clear() on a locked recursive
mutex leads to undefined behaviour.
=> Unlock drakvuf vmi lock before mutex destroy

configure.ac, meson_options.txt, src/main.cpp, src/plugins/Makefile.am, src/plugins/meson.build, src/plugins/output_format/check.cpp, src/plugins/output_format/common.h, src/plugins/output_format/csvfmt.h, src/plugins/output_format/deffmt.h, src/plugins/output_format/jsonfmt.h, src/plugins/output_format/kvfmt.h, src/plugins/plugins.cpp, src/plugins/plugins.h, src/plugins/unixsocketmon/private.h, src/plugins/unixsocketmon/unixsocketmon.cpp, src/plugins/unixsocketmon/unixsocketmon.h
Hi, we have prepared the `unixsocketmon` plugin.
The point is to receive events that pass through unix sockets.
This plugin is presented as an independent one, since its logic is slightly different from the one presented in `socketmon`, since there are various sockets, not only network ones.
A special feature is that you can receive events for "free" from the built-in utilities that are sent to the syslog daemon.
For example,
```json
{
"Plugin": "unixsocketmon",
"TimeStamp": "1664580052.366219",
"PID": 1664,
"PPID": 1396,
"TID": 1664,
"UserName": "UID",
"UserId": 0,
"ProcessName": "/usr/bin/sudo",
"Method": "sock_sendmsg",
"EventUID": "0x19",
"Type": "AF_LOCAL",
"Size": 111,
"Value": "<85>Oct  1 02:20:52 sudo:    ubuntu: TTY=hvc0 ; PWD=/home/astra ; USER=root ; COMMAND=/usr/sbin/useradd …
```
=> Add new plugin: unixsocketmon

src/plugins/socketmon/private.h, src/plugins/socketmon/socketmon.cpp, src/plugins/socketmon/socketmon.h
Hello! socketmon could only log tcp connections that were "complete" meaning that if host was down or invalid, it would not appear in logs. This commit fixes those issues with new tcp hook.
=> socketmon new tcp hook

src/plugins/plugins_ex.h
Drakvuf enables the use of breakpoints with the drakvuf_add_breakpoint function. In order to make this function easier to use by C++ plugins, multiple wrappers are available in plugin_ex.h. However, these wrappers lack the possibility of putting traps of type MEMACCESS.
This pull request :
- removes the default trap type value ;
- sets the trap type value inside each existing wrapper ;
- adds a new wrapper that puts a trap with type MEMACCESS to a GFN.
=>  C++ wrapper to use memory access traps 

src/libdrakvuf/libdrakvuf.h, src/libdrakvuf/win-processes.c
Sometimes, plugins need to access information about a VAD node that is not exposed in the `mmvad_info_t` structure (in my own case, subsection address). 
One way to make additional information available without adding every possible attribute as `mmvad_info_t` fields is to make the VAD address public. Then, a plugin can load and parse the VAD node itself.
=> Add the VAD node address to mmvad_info_t struct

.gitignore, src/plugins/Makefile.am, src/plugins/filetracer/win.cpp, src/plugins/plugin_utils_check.cpp
`FileAttributes` field is `ULONG`. Thus 32 bit only. But with `Windows x64` `vmi_read_addr` reads 64 bit. Thus fix this.
Also add new unit test.
=> filetracer: fix flags parser

configure.ac, src/Makefile.am, src/plugins/output_format/ostream.cpp
https://github.com/tklengyel/drakvuf/blob/64288ad646e2858d2adc834c3f78f9668822b1a4/src/plugins/output_format/ostream.cpp#L125-L130
As show above, `ostream.cpp` handles output format for plugins. By default, it buffers output on non-TTY output devices. This pull request adds an option in `configure.ac` to disable buffering, only for non-TTY devices.
=> Option to disable output buffering on non-tty devices

src/plugins/filetracer/linux.cpp, src/plugins/filetracer/linux.h
refactor get_file_info logic from dynamic dispatching to static one
=>  linux-filetracer: refactor get_file_info logic

src/libdrakvuf/linux-exports.c, src/libdrakvuf/linux-processes.c, src/libdrakvuf/linux.c, src/plugins/filetracer/private.h
use dentry->d_name->name instead of dentry->d_iname as file token name
* 'dentry_addr + offsets[DENTRY_D_NAME] + offsets[QSTR_NAME] + 16' is actually an address of 'dentry_addr->d_iname'
* 'dentry_addr->d_iname' is just a buffer to save allocations that could be not used for large filenames.
* this fixes garbage in extracted file names in case of long file names.
=> linux: fix garbage in long file names (>32 symbols)

src/plugins/procmon/linux.cpp
This is due to differences on Debian and Fedora based images
=> procmon: fix symbol search for linux

src/libusermode/uh-private.hpp, src/libusermode/userhook.cpp
Mapping of `ntdll.dll` and application's executable occur during initial thread creation. Thus `libusermode` could not handle this situation.
This patch fixes the situation.
=> libusermode: hook system dlls

src/libinjector/linux/methods/linux_execve.c
The patch fixes the state handling error which looks like this:
```
1666691703.286596 INT3 Callback @ 0x756a42ca1007. CR3 0x4685801. vcpu 0. TID 2588
1666691703.286602 CPL 0x3
1666691703.286607 Inside INT3 userspace
1666691703.286613 Should not be here
drakvuf: linux/methods/linux_execve.c:278: event_response_t handle_execve(drakvuf_t, drakvuf_trap_info_t *): Assertion `false' failed.
```
=> libinjector: fix parent state restore

src/plugins/hidsim/hid_injection.cpp
Causes compile errors with -Werror, so worth removing.
=> hidsim: Remove unused variable

src/main.cpp, src/plugins/fileextractor/fileextractor.cpp, src/plugins/fileextractor/fileextractor.h, src/plugins/fileextractor/private.h, src/plugins/plugins.cpp, src/plugins/plugins.h
Main feature - files are now extracted along with NtWriteFile call.
New algorithm:
1. After first `NtWriteFile` plugin extract file or create empty;
2. The file is then updated with information from the following `NtWriteFile` calls.
Plugin calculates sha256 hashsum of extracted files.
Not closed files by the end of the analysis are also extracted from the system.
Also plugin was refactored.
=> fileextractor: algorithm modification and refactoring

configure.ac, meson_options.txt, src/libdrakvuf/libdrakvuf.h, src/main.cpp, src/plugins/Makefile.am, src/plugins/meson.build, src/plugins/plugin_utils.cpp, src/plugins/plugin_utils.h, src/plugins/plugin_utils_check.cpp, src/plugins/plugins.cpp, src/plugins/plugins.h, src/plugins/rebootmon/linux-private.h, src/plugins/rebootmon/linux.cpp, src/plugins/rebootmon/linux.h, src/plugins/rebootmon/rebootmon.cpp, src/plugins/rebootmon/rebootmon.h
This plugin allows detect such system reboot events as halt, reboot, power off and can break drakvuf event loop before VM destruction caused by such events.
Use drakvuf command line option "--rebootmon-abort-on-power-off" for enabling loop break mode.
=> rebootmon: new plugin for monitoring of system reboot events

src/main.cpp, src/plugins/fileextractor/fileextractor.cpp, src/plugins/fileextractor/fileextractor.h, src/plugins/fileextractor/private.h, src/plugins/plugins.cpp, src/plugins/plugins.h
I add the ability to exclude some files from extraction. Files is excluding by regular expressions on its path.
Regexps must be provided via option `--fileextractor-exlude-list <path to file with regular expressions>`.
Example file content:
```
^.+\.evtx$
^.+\.pf$
^.*\\windows\\system32\\spool\\drivers\\color\\.+\.icm$
```
=> fileextractor: exclude extracted files by config file

src/plugins/filetracer/private.h, src/plugins/filetracer/win.cpp
filetracer update to get more information about system calls:
- [NtSetInformationFile](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntsetinformationfile) with `FileEndOfFileInformation` flag to get new size of a file
- [NtCreateFile](https://learn.microsoft.com/en-us/windows/win32/api/winternl/nf-winternl-ntcreatefile) `IoStatusBlock` to get final completion status (the status is correct only when the function returns success, otherwise not) - `FILE_SUPERSEDED` (0), `FILE_OPENED` (1) and etc.
=> filetracer update

src/plugins/memaccessmon/memaccessmon.cpp, src/plugins/memaccessmon/memaccessmon.h, src/plugins/memaccessmon/private.h
1. fix plugin: resolve and cache only necessary VADs for addresses in processes instead of traversing all VADs at once and failing on newly created VADs.
2. don't save the number of bytes (from the function arguments) in the cached VAD item.
3. make the `FileName` output parameter optional (don't use the default string "None").
4. add `NtReadVirtualMemoryEx` hook for further Win11 support (see https://github.com/tklengyel/drakvuf/pull/1627).
5. use RAII members in plugin class instead of manual cleanup in dtor.
=> rework memaccessmon

src/plugins/Makefile.am, src/plugins/helpers/profile_guard.h, src/plugins/linkmon/linkmon.cpp, src/plugins/plugins.h
Add RAII wrapper class for `json_object*` retrieved from `json_object_from_file` with automatic resource freeing when out of scope.
Fixed memory leaks in `linkmon` constructor.
=> Linkmon json memory leak fix

src/plugins/hidevm/hidevm.cpp
Use null-terminated strings for `replacement_utf8` and `replacement_utf16` in `replace_object_name`.
Use `UTF-16LE` encoding instead of `UTF-16` to get rid of `BOM`.
Fixed memory leak in `check_and_replace_query_string` on `strQuery`.
=> Hidevm string replacement refactor

src/plugins/socketmon/socketmon.cpp
Fixed memory leak on data->name field
=> socketmon: fix memory leak in udp_send_cb

src/plugins/output_format/common.h, src/plugins/output_format/ostream.h
Force width of two symbols with leading zero in BinaryString output
=> Fix binarystring output

src/plugins/filetracer/linux.cpp
Method `do_truncate` was wrongly processed as `vfs_truncate`
=> filetracer: fix do_truncate callback

src/libusermode/Makefile.am, src/libusermode/check.cpp, src/libusermode/meson.build, src/libusermode/userhook.cpp, src/libusermode/utils.cpp, src/libusermode/utils.hpp
'msi.dll' matches '\Windows\System32\msi.dll', but does not match '\Windows\System32\amsi.dll'. 'system32\msi.dll' matches '\Windows\System32\msi.dll', but does not match '\Windows\nonSystem32\msi.dll'.
=> apimon: match DLL names by a whole path components

src/main.cpp, src/plugins/Makefile.am, src/plugins/fileextractor/fileextractor.cpp, src/plugins/helpers/exclude_matcher.cpp, src/plugins/helpers/exclude_matcher.h, src/plugins/meson.build, src/plugins/plugins.cpp, src/plugins/plugins.h, src/plugins/procdump2/procdump2.cpp, src/plugins/procdump2/procdump2.h
- add `--procdump-exclude-list` option to provide file with regexes for not to dump unnecessary processes;
- add common helper `exclude_matcher` class for use in `fileextractor` and `procdump2` plugins.
=> Procdump exclude

src/plugins/helpers/exclude_matcher.cpp
Use getline to read exclude files.
With istream_iterator lines contains spaces were broken into separate regexes.
=> exclude-matcher: read exclude files line-by-line

src/plugins/syscalls/private.h
Fix copy-paster issue in `prctl_option` map - `PR_SVE_SET_VL` value was listed twice.
=> syscalls: fix copy-paste issue in prctl_option map

src/libhook/hooks/base.hpp, src/libhook/hooks/catchall.cpp, src/libhook/hooks/catchall.hpp, src/libhook/hooks/cpuid.cpp, src/libhook/hooks/cpuid.hpp, src/libhook/hooks/cr3.cpp, src/libhook/hooks/cr3.hpp, src/libhook/hooks/manual.cpp, src/libhook/hooks/manual.hpp, src/libhook/hooks/memaccess.cpp, src/libhook/hooks/memaccess.hpp, src/libhook/hooks/return.cpp, src/libhook/hooks/return.hpp, src/libhook/hooks/syscall.cpp, src/libhook/hooks/syscall.hpp, src/main.cpp, src/plugins/fileextractor/fileextractor.cpp, src/plugins/filetracer/linux.cpp, src/plugins/filetracer/linux.h, src/plugins/filetracer/private.h, src/plugins/plugins.cpp, src/plugins/plugins.h, src/plugins/procmon/linux.cpp, src/plugins/procmon/linux.h, src/plugins/procmon/private.h, src/plugins/procmon/procmon.cpp, src/plugins/procmon/procmon.h
Hi, updating plugins for Linux.
Changelog:
- procmon: fixed memory leaks and exceptions (thanks for @skvl)
- procmon: added a filter file for Linux environment variables
- procmon: handle program startup by file descriptor (syscall `fexecve`)
- procmon: a small refactoring
- filetracer: printing file descriptor in `memfd` callback
- filetracer: a small refactoring
Possible breaking changes:
- procmon: now `do_execveat_common` is an independent callback without mimicry for the parent process
=> Linux plugins update

src/plugins/filetracer/linux.cpp
Add compatibility with 5.12+ kernels for do_truncate trap.
=> filetracer: do_truncate compatibility with 5.12+ kernels

src/xen_helper/Makefile.am
Fix implicit cast errors on clang11:
```
xen_helper.c:184:38: error: request for implicit conversion from ‘void *’ to ‘int (*)(xenforeignmemory_handle *)’ not permitted in C++ [-Werror=c++-compat]
184 |     _xen->xlw.xenforeignmemory_close = dlsym(_xen->xlw.xfm_handle, "xenforeignmemory_close");
```
Fixes the same build error as #1668, but in the suggested way.
=> remove "c++-compat" flag in xen_helper build

src/libdrakvuf/win-exports.c, src/libdrakvuf/win-processes.c
While checking cases with invalid address translation, I got an error where some functions try to read information from PEB when PEB address is 0, so `peb + drakvuf->offsets[SOME_PARAMETER]` is just `drakvuf->offsets[SOME_PARAMETER]` offset, but not a valid address. This happens for kernel processes (System, Registry, Memory Compression, ...).
The patch simply interrupts such functions when there is no PEB for the process.
=> skip kernel processes in functions with PEB parsing

src/libusermode/uh-private.hpp, src/libusermode/userhook.cpp, src/libusermode/userhook_inject.cpp
At the moment, an unreliable algorithm for searching for system DLLs through PEB has been implemented, for at least three reasons:
1) Sometimes PEB's pages are paged out, so reading fails.
2) PEB is user mode memory that is sometimes modified by malware (https://www.cynet.com/attack-techniques-hands-on/defense-evasion-techniques-peb-edition/).
3) Some DLLs (even ntdll) may not be in the PEB list.
The patch implements traverse via VADs.
Also fixed a bug where, after a failed hook attempt, the process is still added to the cache (this is now controlled by the `is_hooked` flag).
=> Search system DLLs for hooking via VADs (not via PEB)

src/libinjector/win/win_injector.c
Following the discussion from https://github.com/tklengyel/drakvuf/pull/1639
- Splitted part of wait_for_target_process_cb into `setup_usermode_trap_x86` and `setup_usermode_trap_x64` to reduce cognitive complexity within that function
- Fixed bug in `setup_usermode_trap_x64` that catched kernel-mode address from trap frame. It was rare case and probably related to page fault inside kernel.
- Added description to `setup_usermode_trap_x86` explaining why we need to use different methods on x64 and x86.
=> libinjector: skip kernel mode trap frame and split wait_for_target_process_cb

src/plugins/exploitmon/exploitmon.cpp, src/plugins/exploitmon/exploitmon.h, src/plugins/exploitmon/private.h
The process name is trimmed to 15 bytes because the EPROCESS structure is not fully initialized in `PsInsertProcess`. We move callback into `PsInsertThread` and check if thread count is 0 meaning the process is being created.
before:
```
exploitmon Time=1676497247.070258,PID=236,PPID=2332,TID=0,ProcessName="backgroundTask",Reason="Process with SYSTEM privileges started"
```
after:
```
[EXPLOITMON] TimeStamp:1694600082.658729 PID:4136 PPID:948 TID:0 UserId:1 ProcessName:"\\Device\\HarddiskVolume2\\Windows\\System32\\backgroundTaskHost.exe" Reason:Process with SYSTEM privileges started
```
=> move token check into PspInsertThread

src/plugins/procmon/linux.cpp, src/plugins/procmon/private.h
Hi, in the last PR (#1688), the correct output of the `ImagePathName` field for `fexecve` was added, however, during testing, some inaccuracies were discovered that this PR corrects
=> procmon: fix fexecve handle

src/libdrakvuf/libdrakvuf.h, src/libdrakvuf/linux.c, src/libdrakvuf/linux.h, src/libdrakvuf/os.c, src/libdrakvuf/os.h, src/libdrakvuf/win.c, src/libdrakvuf/win.h, src/libhook/call_result.hpp, src/plugins/codemon/codemon.cpp, src/plugins/filetracer/linux.cpp, src/plugins/plugins_ex.h, src/plugins/syscalls/linux.cpp
- Add os-specific versions of `set_return_context` methods;
- Method `setResultCallParams` now works correctly for linux hooks.
=> Separate return context for linux and windows hooks

src/plugins/procmon/linux.cpp
Fixed typos in priveleges output
=> procmon: fix typos in priveleges output

package/depends.sh, src/plugins/meson.build
=> Add more plugins

src/plugins/fileextractor/fileextractor.cpp
This error could break injection chain if plugin begin stop.
Based on https://github.com/tklengyel/drakvuf/pull/1777
=> fileextractor: fix BSODs on plugin begin stop

src/libdrakvuf/drakvuf.c, src/libdrakvuf/libdrakvuf.h, src/libinjector/injector_stack.c, src/libinjector/libinjector.h, src/libusermode/userhook_inject.cpp, src/plugins/bsodmon/bsodmon.h, src/plugins/fileextractor/fileextractor.cpp, src/plugins/procdump2/win.cpp
Using callback function address to identify injection context is bad idea because of C++ lambda wrappers used in libhook. This result in hard to debug errors in run time.
=> libdrakvuf: fix injection manager

src/libdrakvuf/linux-exports.c, src/libdrakvuf/vmi.c, src/plugins/procmon/linux.cpp
Added memory freeing in several places where a methods derived from `vmi_read_str` was used.
=> Fix some vmi_read_str memory leaks

src/plugins/fileextractor/private.h, src/plugins/fileextractor/win.cpp, src/plugins/fileextractor/win.h
- First `NtWriteFile` read was moved to return hook (caused errors in extracted file)
- Added `NtWriteFile` error check
=> fileextractor: move NtWriteFile to return hook

src/libinjector/linux/linux_utils.c
Due to changed vdso layout in modern kernels (at least 6.2), linux injector when parsing vdso in `find_syscall` can first find the address of the trap we are already standing on. This leads to a violation of the injection logic.
So in this case we can simply skip first occurence of `syscall` call in vdso and try to find next.
=> injector: push apart overlapping traps

src/plugins/memdump/memdump.cpp
I found that memdump plugin always gets RSP from trap frame even if stack traversal is triggered by usermode trap. This lead to incorrect dumping because kernel trap frame doesn't have correct usermode stack pointer while we're trapped in usermode. In this case drakvuf fails to find the real caller of the hooked function.
After adding some debug logs to the failed dumping attempt:
```
1717157477.234616 [MEMDUMP DEBUG] Inspecting stack (is_32bit=1, stack_ptr=5dfd800)
1717157477.234627 [MEMDUMP DEBUG] current rsp=5dfd508, current rip=77124141
```
we can see that dumping failed because real stack pointer from vCPU context was at 5dfd508, but stack was read starting from 5dfd800 that was address left in trap frame after some previous syscall.
This PR checks if current RSP/RIP is in …
=> memdump: Get stack pointer from registers instead of trapframe for usermode hooks

src/libdrakvuf/drakvuf.c
Hi!
This fix is addressing issues related with target process crash/hang caused by injector e.g. https://github.com/tklengyel/drakvuf/issues/925, https://github.com/tklengyel/drakvuf/issues/1758
I've spent hours on debugging injector crashes and I found a bit surprising bug: hijacked thread context is incorrectly restored because two registers were missing in `drakvuf_set_vcpu_gprs` function: RSI and RDI.
These registers are crucial because according to [Microsoft x64 ABI convention](https://learn.microsoft.com/en-us/cpp/build/x64-software-conventions?view=msvc-170&redirectedfrom=MSDN#register-volatility-and-preservation), they're non-volatile registers that should be preserved by the callee. Of course the bug leads to the corruption of targeted process, usually followed by a crash.
I …
=> Fix injector: drakvuf_set_vcpu_gprs forgot about RSI and RDI

src/plugins/socketmon/private.h, src/plugins/socketmon/socketmon.cpp
* add Windows 11 23H2 x64 TCP and UDP field offsets
* add Windows Server 2019 TCP and UDP field offsets
* stop plugin on destruction
=> socketmon: extend Windows builds support

meson_options.txt, src/plugins/meson.build, src/plugins/output_format/ostream.h
The Meson build system was missing the `disable-output-buffering` option, which is available in the Make build system. This commit adds the `disable-output-buffering` option to the Meson build system.
=> Fix regression: Missing "disable-output-buffering" option since meson builds

src/plugins/output_format/ostream.cpp
In this PR i fixed possible overwrite of trace events: `write` method can return fewer bytes than requested. In this case were gonig to the second round in the loop and try to write the rest of the buffer, but again use `pbase()` pointer that points to begin of buffer and write wrong part of buffer.
Now we track position and remaining size correct.
=> ostream: fix potential overwrite in StrBuf::sync_impl

src/plugins/socketmon/socketmon.cpp, src/plugins/socketmon/socketmon.h
Applies the recommandation of @psrok1 at https://github.com/tklengyel/drakvuf/issues/1613#issuecomment-2248031590 of implementing usermode hooking for socketmon plugin using libusermode.
This allows a user to have basic network and DNS monitoring, even when no process has loaded the `dnsapi.dll` library yet, which should fix issue #1613, assuming that [this comment](https://github.com/tklengyel/drakvuf/issues/1613#issuecomment-1440190721) is highlithing the real issue.
=> Modernize usermode hooking using libusermode

src/plugins/socketmon/private.h, src/plugins/socketmon/socketmon.cpp
Adds offsets for TCP and UDP for socketmon on Windows 10 1909.
=> socketmon: extend Windows builds support for Win10 1909

configure.ac
Remove explicit CXXFLAGS assignment in configure.ac, as `gnu++17` standard  is determined by line `AX_CXX_COMPILE_STDCXX([17], [ext], [mandatory])` (`[17]` and `[ext]`, https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx.html); and if flag is described here - it overlaps CXXFLAGS flag, that you can pass to `configure` script.
=> remove explicit CXXFLAGS assignment

src/libhook/hooks/base.cpp, src/libhook/hooks/base.hpp, src/libhook/hooks/catchall.cpp, src/libhook/hooks/catchall.hpp, src/libhook/hooks/cpuid.cpp, src/libhook/hooks/cpuid.hpp, src/libhook/hooks/cr3.cpp, src/libhook/hooks/cr3.hpp, src/libhook/hooks/manual.cpp, src/libhook/hooks/manual.hpp, src/libhook/hooks/memaccess.cpp, src/libhook/hooks/memaccess.hpp, src/libhook/hooks/return.cpp, src/libhook/hooks/return.hpp
At first, `clang-tidy-19` static analyzer shows `bugprone-use-after-move` warnings on move constructors in classes, derives `BaseHook`. Also, `params_` members was not transferred at all.
After that i saw that move semantic for `libhook` hooks is completely not used in actual code, as we use RAII to deal with these hooks and do not transfer ownership of them.
So i delete explicitly move constructors and move operators in base and derived hooks classes, as already been done in `SyscallHook` class. This will prevent porssible errors when working with these hooks,
=> Remove unused move constructors and assignment operators from libhook

src/libdrakvuf/win.c
`win_get_object_type_index` returned false for Windows version != 10 even when successful.
It corrects the mistake I made in the previous fix #1822.
=> win_get_object_type_index fix

src/libinjector/win/methods/win_exitthread.c, src/libinjector/win/win_injector.c, src/libinjector/win/win_utils.h
Exit thread injection method and related `--exit-injection-thread` Drakvuf parameter doesn't work because `initialize_injector_functions` returns successfully only when `injector->exec_func` is set. 
INJECT_METHOD_EXITTHREAD used dedicated `exit_thread` pointer instead which is incorrect regarding the convention followed by other injection methods.
This PR changes the `RtlExitUserThread` pointer assignment to `injector::exec_func` and removes unused `injector::exit_thread`
=> Fix EXITTHREAD injector method used by --exit-injection-thread

src/libdrakvuf/win.c
This PR ensures that DRAKVUF doesn't try to resolve `ObTypeIndexTable` and `ObpInfoMaskToOffset` kernel symbols on Windows Vista, as those are not present in that OS version.
This small change allows several plugins such as `regmon`, `objmon`, and others to work under Windows Vista SP2 x64 and x86 (see issue [#1831](https://github.com/tklengyel/drakvuf/issues/1831) for more information). 
Further adjustments to plugin behavior for Vista support may follow in a later PR - for instance for `callbackmon` that fails at startup.
=> Support for Windows Vista: skip ObTypeIndexTable and ObpInfoMaskToOffset for Vista

src/plugins/apimon/apimon.cpp, src/plugins/apimon/apimon.h
When hooked API function is called, apimon stores the return (post) hook in `plugin->ret_hooks` hashmap. Unfortunately, the key in that hashmap is composed only from PID and TID, so when hooked function calls another hooked function, the previous return hook reference is overwritten.
When hook reference kept by `plugin->ret_hooks` is overwritten, the previous unique_ptr reference is destroyed, so the return hook is unhooked. Finally, we lose information about the original call and see only the last nested call.
**What's changed**
I changed `make_hook_id` function to include stored target_rsp for pre-hook to actually identify a function call. I have included only 18-bits part of PID/TID (assuming 2 LSB are always zeroed as PID/TID are aligned to 4) and 32-bit part of the RSP. I believe …
=> Fix: changed make_hook_id to not overwrite return hook when apicall was nested

src/plugins/rpcmon/rpcmon.cpp
rpcmon parse_RPC_MESSAGE method reads the pointer to RPC_MESSAGE as the struct itself, and tries to parse some address as GUID for example:
`{"Arguments": ["RpcMessage=119093061232"], "Extra": [{"InterfaceId": "\"00007FFC-0000-0000-0000-000000000000\""}], "ExtraNum": [{"ProcNum":46}]}`
fix by reading the pointer first and then reading the struct
=> fix parsing of RPC_MESSAGE struct

src/plugins/output_format/common.h, src/plugins/output_format/csvfmt.h, src/plugins/output_format/deffmt.h, src/plugins/output_format/jsonfmt.h, src/plugins/output_format/kvfmt.h
Adds a Subkey output format needed to show syscall arguments in a nested structure, suggested in #1796
It can be used like this (not included in this pr yet):
```diff
index ff940f3..11ab88c 100644
--- a/src/plugins/syscalls/private_2.h
+++ b/src/plugins/syscalls/private_2.h
@@ -131,7 +131,8 @@ public:
bool disable_sysret;
std::unordered_set<std::string> filter;
-    std::vector<std::pair<char const*, fmt::Aarg>> fmt_args;
+    std::vector<std::pair<std::string, fmt::Aarg>> fmt_args;
```
```diff
index 01dec3e..9ca616f 100644
--- a/src/plugins/syscalls/win.cpp
+++ b/src/plugins/syscalls/win.cpp
@@ -829,7 +829,7 @@ void win_syscalls::print_syscall(
keyval("PreviousMode", priv_mode_opt),
keyval("FromModule", from_dll_opt),
keyval("FromParentModule", from_parent_dll_opt),
- …
```
=> Add a Subkey to output format
