tklengyel/drakvuf

- src/drakvuf.h
- src/injector.c
- src/injector_standalone.c
- src/output.h
- src/vmi.h
- src/win-symbols.c
- src/win-symbols.h
> APC based injection for 32-bit Windows 7 is more reliable then

- configure.ac
- src/plugins/Makefile.am
- src/plugins/exmon/exmon.c
- src/plugins/exmon/exmon.h
- src/plugins/exmon/private.h
- src/plugins/private.h
... and extracts information about the trap frame.
Using the simplified plugin integration.
> Added EXMON that hooks KiDispatchException 

- src/drakvuf.c
- src/plugins/exmon/exmon.c
- src/plugins/exmon/exmon.h
- src/plugins/filedelete/filedelete.c
- src/plugins/filedelete/filedelete.h
- src/plugins/filetracer/filetracer.c
- src/plugins/filetracer/filetracer.h
- src/plugins/objmon/objmon.c
- src/plugins/objmon/objmon.h
- src/plugins/plugins.c
- src/plugins/plugins.h
- src/plugins/poolmon/poolmon.c
- src/plugins/poolmon/poolmon.h
- src/plugins/private.h
- src/plugins/syscalls/syscalls.c
- src/plugins/syscalls/syscalls.h
Merge plugin_init and plugin_start into a single plugin_start function, and rename plugin_close to plugin_stop.
> Simplify plugin API

- src/libdrakvuf/vmi.c
> Force-reset all EPT permissions on shutdown

- src/drakvuf.c
- src/libdrakvuf/injector.c
Don't start monitoring if injection didn't work and fail if injected PID is >= 5000 which is caused by some random crash of the hijacked app. Root cause is still under investigation.
> Injector work

- configure.ac
- src/dirwatch/Makefile.am
- src/dirwatch/dirwatch.c
- tools/cleanup.sh
- tools/drakvuf.sh
- tools/preconfig.sh
new files are created. When a new file is detected, a DRAKVUF instance
can be launched.
> Add dirwatch tool which hooks on a target folder for events when

- src/dirwatch/dirwatch.c
- tools/clone.pl
- tools/drakvuf.sh
- tools/network-setup.sh
- tools/preconfig.sh
- tools/tcpdump.sh
Move completed file to processed folder even if it failed to run and force cleanup after each run. Redirect stderr properly to log files.
> Tweak dirwatch

- src/main.cpp
> Add back injection to main

- src/plugins/filedelete/filedelete.cpp
A small change to natively extract filenames as requested in https://github.com/tklengyel/drakvuf/issues/98. Output will be in the following format (CSV and default):
```
filedelete,0,0x4d2f1a0,svchost.exe,"\Windows\Prefetch\TASKHOST.EXE-7238F31D.pf"
[FILEDELETE] VCPU:0 CR3:0x4d2f2e0,explorer.exe "\Users\b\Desktop\Új szöveges dokumentum.txt"
```
As you can see funny Hungarian characters and spaces in paths are handled (although I'm not sure about if CSV parsers treat `\` as escape character inside quotes...)
> Native file name extraction for FILEDELETE

- src/libdrakvuf/win-processes.c
and use dtb instead of PID based lookup
> Don't return true in drakvuf_get_module_list if modulelist is 0

- src/drakvuf.cpp
- src/drakvuf.h
- src/injector.c
- src/libdrakvuf/drakvuf.c
- src/libdrakvuf/injector.c
- src/libdrakvuf/libdrakvuf.h
- src/libdrakvuf/private.h
- src/libdrakvuf/vmi.c
- src/libdrakvuf/win-processes.c
- src/main.cpp
- src/plugins/plugins.h
> Runtime configuration of plugin/debug output

- configure.ac
> Define stdc format macros through configure

- src/libinjector/injector.c
Entry and return traps are the same for 64-bit injection so no need to remove/readd the same trap twice.
> 64-bit injector optimization

- src/libdrakvuf/drakvuf.c
- src/libdrakvuf/vmi.c
- src/main.cpp
> Injector should leave the VM unpaused

- src/libdrakvuf/vmi.c
> Use new vmi_swap_events API

- src/libdrakvuf/private.h
- src/libdrakvuf/vmi.c
> Selectively call memaccess traps for matching permissions

- src/libdrakvuf/vmi.c
Fix for Issue #193 
As _VMI_MEMACCESS_INVALID_ value is 0, I can merge **old_access** and _VMI_MEMACCESS_RW_ using OR.
If you want, I can add an **if** statement to check **old_access** value (different from _invalid_) and I can add a **PRINT_DEBUG** when the memaccess is merged (when **s** isn't _null_).
> Fix page rights when placing a breakpoint

- src/libdrakvuf/vmi.c
> Fix breakpoints on execute trapped page

- src/libdrakvuf/vmi.c
On x86 the breakpoint instruction may have several superfluous prefixes attached that don't actually do anything other then changing the address and length of the reported breakpoint. In this patch we fix the reinjection behavior to properly check the right address when the reported insn_length is greater then 1 (caused by prefixes). This also requires an update of LibVMI to the latest drakvuf branch.
> Handle prefixed int3 instructions appropriately

- src/libdrakvuf/vmi.c
> Move container check to appropriate location

- src/drakvuf.cpp
- src/drakvuf.h
- src/libdrakvuf/Makefile.am
- src/libdrakvuf/drakvuf.c
- src/libdrakvuf/libdrakvuf.h
- src/libdrakvuf/os.c
- src/libdrakvuf/os.h
- src/libdrakvuf/private.h
- src/libdrakvuf/rekall-profile.c
- src/libdrakvuf/rekall-profile.h
- src/libdrakvuf/vmi.c
- src/libdrakvuf/vmi.h
- src/libdrakvuf/win-offsets-map.h
- src/libdrakvuf/win-offsets.h
- src/libdrakvuf/win-processes.c
- src/libdrakvuf/win.c
- src/libdrakvuf/win.h
- src/main.cpp
- src/plugins/plugins.cpp
- src/plugins/plugins.h
- src/plugins/syscalls/syscalls.cpp
Adding scaffolding to support Linux. Plugin support is only syscalls / cpuidmod / debugmon. KASLR not yet supported.
> Linux support

- .gitignore
- .travis.yml
- configure.ac
- src/libdrakvuf/drakvuf.c
- src/libdrakvuf/vmi.c
- src/libinjector/injector.c
- src/plugins/Makefile.am
- src/plugins/filetracer/filetracer.cpp
- src/plugins/plugins.cpp
- src/plugins/socketmon/private.h
- src/plugins/socketmon/socketmon.cpp
- src/plugins/socketmon/socketmon.h
Monitor TCP and UDP sockets on Windows using the pool allocations.
```
[SOCKETMON] VCPU:1 CR3:0x1f3ae000,svchost.exe SessionID:0 Owner:svchost.exe SessionID:0 UDPv4 192.168.2.173:68
[SOCKETMON] VCPU:0 CR3:0x46a01000,iexplore.exe SessionID:1 Owner:iexplore.exe SessionID:1 UDPv4 127.0.0.1:57464
[SOCKETMON] VCPU:1 CR3:0x48499000,iexplore.exe SessionID:1 Owner:iexplore.exe SessionID:1 UDPv4 127.0.0.1:57465
[SOCKETMON] VCPU:1 CR3:0x187000,Idle SessionID:-1 Owner:iexplore.exe SessionID:1 TCPv4 State:established Local:192.168.2.173:49158 Remote:13.107.21.200:80
[SOCKETMON] VCPU:0 CR3:0x187000,Idle SessionID:-1 Owner:iexplore.exe SessionID:1 TCPv4 State:established Local:192.168.2.173:49160 Remote:204.79.197.203:80
[SOCKETMON] VCPU:1 CR3:0x21f66000,csrss.exe SessionID:1 Owner:iexplore.exe …
```
> Socketmon plugin

- src/libinjector/injector.c
Should fix all remaining issues resulting crashes (#158)
> Ensure threadid match on injection return path

- src/plugins/filetracer/filetracer.cpp
- src/plugins/filetracer/filetracer.h
> Use syscalls for filetracing

- src/libdrakvuf/private.h
- src/libdrakvuf/vmi.c
- src/xen_helper/xen_helper.c
- src/xen_helper/xen_helper.h
> Properly get and set maxmem and gpfns

- src/drakvuf.cpp
- src/drakvuf.h
- src/libdrakvuf/drakvuf.c
- src/main.cpp
- src/plugins/plugins.h
- src/plugins/socketmon/private.h
- src/plugins/socketmon/socketmon.cpp
- src/plugins/socketmon/socketmon.h
Use rekall profile for tcpip.sys and support up to Windows 10
> Rework socketmon plugin

- tools/rpcserver.py
- tools/rpctestclient.py
Simple XMLRPC server to receive files to be used with dirwatch and send results after processed.
> Add RPC server and test client code

- src/plugins/socketmon/socketmon.cpp
> socketmon: exit nicely if no Rekall profile present

- src/libinjector/injector.c
@aoshiken can you give this branch a try?
Fixes #320
> Refresh LibVMI memsize caches

- src/libdrakvuf/vmi.c
- src/plugins/regmon/regmon.cpp
> Pass current process base address to trap info

- src/drakvuf.cpp
- src/drakvuf.h
- src/injector.c
- src/libinjector/injector.c
- src/libinjector/libinjector.h
- src/main.cpp
This allows to pass a path for any file (for example docx) and automatically open it if certain application is installed.
> Add option to run files via "shell32.dll!ShellExecuteA"

- src/plugins/filetracer/filetracer.cpp
- src/plugins/filetracer/filetracer.h
Also
* Refactor traps initialization in FILETRACER plugin.
* Take into account the RootDirectory value in a file path in the FILETRACER plugin.
* Print syscall name in FILETRACER plugin.
> Add handling of file renames in FILETRACER plugin.

- src/drakvuf.cpp
- src/drakvuf.h
- src/main.cpp
- src/plugins/filedelete/filedelete.cpp
- src/plugins/filedelete/filedelete.h
- src/plugins/plugins.h
Save some metadata (only filename for now) for each extracted file.
> Extract new or modified files from sandbox in FILEDELETE plugin.

- configure.ac
- src/plugins/Makefile.am
- src/plugins/plugins.cpp
- src/plugins/procmon/procmon.cpp
- src/plugins/procmon/procmon.h
Currently supports only process creation via NtCreateUserProcess
and only on x64 arch.
> Added PROCMON plugin for watching life cycle of the processes.

- src/plugins/syscalls/syscalls.cpp
Potential NULL-pointer dereference on wsc
> Fix CID 189192

- src/libinjector/injector.c
Inject prints program and arguments separately
> Inject prints program and arguments separately

- src/libinjector/injector.c
For 32 bit Windows:
Added stack and parameters allocated on stack alignment to 64 bytes.
Added function for putting string on stack with alignment to 64 bytes.
> Added stack alignment and function putting string on stack for 32 bit Windows

- src/libdrakvuf/drakvuf.c
- src/libdrakvuf/libdrakvuf.h
- src/libinjector/libinjector.h
- src/plugins/filetracer/filetracer.cpp
- src/plugins/plugins.h
- src/plugins/procmon/procmon.cpp
Added:
utility functions for unicode strings
vmi_lock_guard
> Added utility functions for unicode strings and vmi_lock_guard

- src/injector.c
- src/plugins/socketmon/private.h
- src/plugins/socketmon/socketmon.cpp
- src/plugins/socketmon/socketmon.h
Added DNS resolution calls handling for:
dnsapi.dll!DnsQuery_[W,A,UTF8] - for all Windows versions
dnsapi.dll!DnaQueryEx[A,W] - for Windows 7
dnsapi.dll!DnaQueryEx - for Windows 10
> Added DNS resolution call handling

- src/libinjector/injector.c
- src/libinjector/libinjector.h
This allows to call those functions from other places such as plugins.
More over fix stack alignment bug.
> Make universal functions to setup stack accessable globally

- src/plugins/filedelete/filedelete.h
- src/plugins/filedelete/filedelete2.cpp
Reading such files result in `STATUS_PENDING'.
> Add `ZwWaitForSingleObject()' injection for asynchronous files

- src/libdrakvuf/drakvuf.c
- src/libdrakvuf/libdrakvuf.h
- src/libdrakvuf/private.h
- src/libdrakvuf/vmi.c
- src/libdrakvuf/vmi.h
- src/plugins/socketmon/private.h
- src/plugins/socketmon/socketmon.cpp
- src/plugins/socketmon/socketmon.h
- src/xen_helper/xen_helper.c
- src/xen_helper/xen_helper.h
Also fix assorted performance issues with socketmon.
> Re-add event fd API with performance fixes

- src/plugins/socketmon/private.h
- src/plugins/socketmon/socketmon.cpp
Added support of 32bit windows to socketmon
> Added support of 32bit windows to socketmon

- src/plugins/regmon/regmon.cpp
Added printing of regmon values, written to register
> Added printing of regmon values, written to register

- configure.ac
- src/drakvuf.cpp
- src/plugins/Makefile.am
- src/plugins/bsodmon/bsodmon.cpp
- src/plugins/bsodmon/bsodmon.h
- src/plugins/plugins.cpp
Allows to get notification of bug check (aka BSOD).
*NOTE* For some reason on _x86_ there is no notification. Debug in progress.
> BSOD monitor

- src/drakvuf.cpp
- src/drakvuf.h
- src/libdrakvuf/drakvuf.c
- src/libdrakvuf/libdrakvuf.h
- src/libdrakvuf/os.c
- src/libdrakvuf/private.h
- src/libdrakvuf/rekall-profile.c
- src/libdrakvuf/rekall-profile.h
- src/libdrakvuf/win.c
- src/libinjector/injector.c
- src/main.cpp
- src/plugins/bsodmon/bsodmon.cpp
- src/plugins/bsodmon/bsodmon.h
- src/plugins/delaymon/delaymon.cpp
- src/plugins/exmon/exmon.cpp
- src/plugins/filedelete/filedelete.cpp
- src/plugins/filetracer/filetracer.cpp
- src/plugins/objmon/objmon.cpp
- src/plugins/plugins.h
- src/plugins/poolmon/poolmon.cpp
- src/plugins/private.h
- src/plugins/procmon/procmon.cpp
- src/plugins/regmon/regmon.cpp
- src/plugins/socketmon/socketmon.cpp
- src/plugins/ssdtmon/ssdtmon.cpp
- src/plugins/syscalls/syscalls.cpp
Loading every rekall jsons once per drakvuf launch
> Loading every rekall jsons once per launch

- src/libinjector/injector.c
Lock in injection callbacks only.
> Do not lock drakvuf for the whole injection process.

- src/drakvuf.cpp
- src/libdrakvuf/drakvuf.c
- src/libdrakvuf/libdrakvuf.h
- src/libdrakvuf/os.c
- src/libdrakvuf/os.h
- src/libdrakvuf/win-processes.c
- src/libdrakvuf/win.c
- src/libdrakvuf/win.h
- src/plugins/plugins.h
- src/plugins/socketmon/private.h
- src/plugins/socketmon/socketmon.cpp
- src/plugins/socketmon/socketmon.h
Make full initialization in constructor (while VM is paused).
Remove number of tries and other instabilities.
> SOCKETMON plugin initialization refactored.

- src/libinjector/injector.c
- src/libinjector/libinjector.h
- src/libinjector/private.h
- src/plugins/filedelete/filedelete2_helpers.cpp
* Remove unused code from libinjector
* Untie setup_stack functions from access context
> Remove unused code from libinjector

- src/plugins/filedelete/filedelete.cpp
> Filedelete: update printing file object flags in KV format

- src/libinjector/injector_stack.c
- src/plugins/filedelete/filedelete.cpp
This allows correlate file artifacts and filedelete logs.
> FILEDELETE: Print sequence numbers

- src/libdrakvuf/libdrakvuf.h
- src/libdrakvuf/os.c
- src/libdrakvuf/os.h
- src/libdrakvuf/win-registry.c
- src/libdrakvuf/win.h
- src/plugins/regmon/regmon.cpp
* Remove process_arg argument. This info is contained in info argument already.
* Change type of key_handle argument. This is not an address.
> Purify drakvuf_reg_keyhandle_path interface

- src/plugins/filedelete/filedelete.cpp
- src/plugins/filetracer/filetracer.cpp
- NtSetInformationFile marks file for deletion on NtClose.
- Fall back to parsing cache manager if start_readfile() fails.
- Print intention to delete file in filetracer plugin.
> FILEDELETE: fix file extraction on NtSetInformationFile

- src/drakvuf.cpp
- src/libdrakvuf/drakvuf.c
- src/libdrakvuf/vmi.c
- src/libdrakvuf/win-handles.c
- src/libinjector/injector.c
- src/plugins/cpuidmon/cpuidmon.cpp
- src/plugins/debugmon/debugmon.cpp
- src/plugins/delaymon/delaymon.cpp
- src/plugins/procmon/procmon.cpp
- src/plugins/socketmon/socketmon.cpp
removed ';' that were present at the closing braces of switch and if stmts.
> Empty statements removed -> redundant " ; "

- src/plugins/socketmon/socketmon.cpp
* Add quotes for Owner field
* Add missing commas in JSON output format
> SOCKETMON: Fixed output format

- src/plugins/socketmon/socketmon.cpp
I make a bug in #580. This MR fixes it.
> SOCKETMON: Fix protocol string

- src/dirwatch/dirwatch.c
I have changed only one sprintf to snprintf for now. I just wanted to test whether it is okay or not.
> Update to snprintf

- src/plugins/envmon/envmon.cpp
- src/plugins/envmon/envmon.h
- src/plugins/envmon/private.h
- src/plugins/procmon/procmon.cpp
- src/plugins/procmon/procmon.h
New handler for GetAdaptersAddresses, WNetGetProviderNameW.
Other changes is plugin conversion to use plugin_ex.
> Switch few exists plugin to use plugin_ex

- configure.ac
- src/plugins/Makefile.am
- src/plugins/dkommon/dkommon.cpp
- src/plugins/dkommon/dkommon.h
- src/plugins/plugins.cpp
This is the first and simplest implementation of the plugin. It checks that current process is self-cycled.
Thus if rootkit would hide two sequential processes then the check does not notice this.
> Add plugin to check for hidden processes (DKOM)

- configure.ac
- src/main.cpp
- src/plugins/Makefile.am
- src/plugins/envmon/envmon.cpp
- src/plugins/librarymon/librarymon.cpp
- src/plugins/plugins.cpp
- src/plugins/plugins_ex.cpp
- src/plugins/plugins_ex.h
- src/plugins/procmon/procmon.cpp
- src/plugins/wmimon/wmimon.cpp
- src/plugins/wmimon/wmimon.h
New plugin WMIMon that is monitor a basic WMI requests as IWbemlocator::ConnectServer, IWbemServices::ExecQuery, IWbemServices::GetObject, IWbemServices::ExecMethod. But only for x64 platform. We found a bug a rekall profile for syswow64/ole32.dll. Also I change a plugins_ex.h and plugins_ex.cpp and other plugins that depend of them. I did a class pluginex more resemble for classes of std.
> New plugin WMIMon

- src/libdrakvuf/libdrakvuf.h
- src/libdrakvuf/win-processes.c
- src/libinjector/injector.c
* Fix possible null pointer dereference
* Add printing of crashed processes while injection
> Fix print injection status

- src/libdrakvuf/win-processes.c
- src/plugins/crashmon/crashmon.cpp
> Fix memory leaks in crashmon

- src/plugins/crashmon/crashmon.cpp
Implement the JSON output for `crashmon`
> crashmon: add json output

- .travis.yml
Ticket tracker: https://jira.sonarsource.com/browse/CPP-2027
> Sonar broken on bionic, stick with Xenial

- src/plugins/memdump/memdump.cpp
- src/plugins/memdump/memdump.h
- src/plugins/memdump/private.h
- src/plugins/memdump/userhook.cpp
Refactor code in `memdump`, introduce some additional heuristics and deduplicate memory dumps by their hash.
> memdump: better heuristics in memdump plugin, deduplicate dumps by hash

- src/libdrakvuf/vmi.c
Working on issue https://github.com/tklengyel/drakvuf/issues/679, this PR removes some of the direct calls made to Xen libraries, using LibVMI as an abstraction layer instead.
The only call which is missing is `vmi_slat_set_domain_state(true)`, because it's already handled in `xen_helper.c:xen_enable_altp2m()`.
This function should be integrated in Libvmi as well. (https://github.com/tklengyel/drakvuf/pull/681#issuecomment-519947749)
> vmi: replace xc_altp2m calls by vmi_slat functions from LibVMI

- .travis.yml
- src/plugins/Makefile.am
> Remove switch-enum from compiler checks in plugins

- src/plugins/debugmon/debugmon.cpp
- src/plugins/socketmon/socketmon.cpp
> Fix debugmon and socketmon JSON output

- src/dirwatch/dirwatch.c
- src/libdrakvuf/drakvuf.c
- src/libdrakvuf/os.c
- src/libdrakvuf/rekall-profile.c
- src/libdrakvuf/vmi.c
- src/libdrakvuf/win-registry.c
- src/libdrakvuf/win.c
- src/libinjector/injector_stack.c
- src/libinjector/linux_injector.c
- src/libinjector/win_injector.c
- src/plugins/exmon/exmon.cpp
- src/plugins/filedelete/filedelete.cpp
- src/plugins/memdump/userhook.cpp
- src/plugins/regmon/regmon.cpp
- src/plugins/socketmon/socketmon.cpp
- src/plugins/syscalls/syscalls.cpp
- src/plugins/windowmon/windowmon.cpp
- src/xen_helper/xen_helper.c
Allows to handle oom situations gracefully
> Use g_try_malloc0

- src/libdrakvuf/vmi.c
> Deactivate remapped gfn when removing memaccess trap

- src/libdrakvuf/vmi.c
Retire experimental white-list based approach
/cc @sasza8
> Fall-back to memory access based monitoring on certain writes

- src/plugins/memdump/private.h
- src/plugins/memdump/userhook.cpp
Tracking WinAPI calls with their arguments and return value
> behavioral analysis

- src/libdrakvuf/vmi.c
- src/libinjector/win_injector.c
- src/libinjector/win_private.h
- src/main.cpp
- src/plugins/filedelete/filedelete.cpp
* Add verbose output for file extraction failures
* Add "help" command-line argument
> Refactoring and debug output

- src/libdrakvuf/vmi.c
- src/libinjector/win_injector.c
- src/libinjector/win_private.h
* Fix missing proc_data.tid in proc_mem_cb 
* Fix initializtion of injector functions for Windows x86
> Fixes for x86

- src/plugins/filetracer/filetracer.cpp
- src/plugins/filetracer/private.h
- src/plugins/plugin_utils.cpp
- src/plugins/plugin_utils.h
* plugins/procmon: add hook for NtAdjustPrivilegesToken
* plugins/filetracer: hook return from NtCreateFile to get file handle
> Add new hooks

- src/libdrakvuf/libdrakvuf.h
- src/libinjector/libinjector.h
Optimizes C++ code as C functions never throw exceptions
> Specify noexcept for C libraries

- .gitignore
- src/Makefile.am
- src/proc_stat.cpp
This is used to determine most suitable PID and TID to inject into.
This is instead of https://github.com/libvmi/libvmi/pull/869
> Add tool to catch processes execution statistics in Windows

- .gitignore
- src/plugins/socketmon/private.h
- src/plugins/socketmon/socketmon.cpp
- src/plugins/socketmon/socketmon.h
* Remove unrelaible parts (tcp listener and udp seems not working to me)
* Redefine structures for tcp endpoint for Windows 8.1 and Windows 10 (1803)
* Reverse and leave single breakpoint to tcpip:TcpCreateAndConnectTcbComplete
> Fix socketmon

- src/plugins/ssdtmon/ssdtmon.cpp
SSDTmon assumed 64-bit offsets for x64 Windows.
> SSDTmon: The entries in the SSDT are 32-bit offsets from the SSDT base

- src/libdrakvuf/libdrakvuf.h
- src/libdrakvuf/os.c
- src/libdrakvuf/os.h
- src/libdrakvuf/win.c
- src/plugins/Makefile.am
- src/plugins/memdump/crypto.cpp
- src/plugins/memdump/crypto.h
- src/plugins/memdump/private.h
- src/plugins/memdump/userhook.cpp
Custom hook for CryptGenKey from cryptoapi allowing to extract generated key bytes
> Key extraction for CryptGenKey

- tools/demangle.py
Interim solution while https://github.com/volatilityfoundation/volatility3/issues/157 is being resolved
> Add demangle.py to post-process Volatility ISTs

- src/plugins/memdump/userhook.cpp
Comma should not come after the plugin value in KV format(Other plugins follow this rule)
PID and PPID values added to KV format
> Minor correction in output format

- .travis.yml
- Makefile.am
- src/libusermode/Makefile.am
https://travis-ci.org/github/tklengyel/drakvuf/jobs/661137329
/cc @sasza8 @icedevml
> Fix make dist error and add Travis check for it

- src/Makefile.am
- src/libdrakvuf/libdrakvuf.h
- src/libdrakvuf/vmi.c
- src/libinjector/linux_injector.c
- src/libinjector/win_injector.c
- src/libusermode/Makefile.am
- src/plugins/Makefile.am
- src/plugins/output_format.h
- src/plugins/procmon/procmon.cpp
> Deprecate GTimeVal use

- src/libdrakvuf/vmi.c
- src/plugins/filedelete/filedelete.cpp
- src/plugins/filedelete/filedelete.h
- src/plugins/filedelete/private.h
- src/plugins/plugin_utils.cpp
- src/plugins/plugin_utils.h
- src/plugins/plugins_ex.h
- src/plugins/procdump/private.h
- src/plugins/procdump/procdump.cpp
* It is possible to pass `FILE_DELETE_ON_CLOSE` flag in `CreateOptions`/`OpenOptions` to delete file.
* Use `attached process` to make it more accurate
> filedelete: hook NtCreateFile/NtOpenFile

- src/libdrakvuf/libdrakvuf.h
- src/libdrakvuf/private.h
- src/libdrakvuf/vmi.c
- src/plugins/bsodmon/bsodmon.cpp
- src/plugins/clipboardmon/clipboardmon.cpp
- src/plugins/cpuidmon/cpuidmon.cpp
- src/plugins/crashmon/crashmon.cpp
- src/plugins/debugmon/debugmon.cpp
- src/plugins/delaymon/delaymon.cpp
- src/plugins/dkommon/dkommon.cpp
- src/plugins/exmon/exmon.cpp
- src/plugins/filedelete/filedelete.cpp
- src/plugins/filetracer/filetracer.cpp
- src/plugins/librarymon/librarymon.cpp
- src/plugins/memdump/memdump.cpp
- src/plugins/plugins_ex.h
- src/plugins/procdump/procdump.cpp
- src/plugins/procmon/procmon.cpp
- src/plugins/regmon/regmon.cpp
- src/plugins/socketmon/socketmon.cpp
- src/plugins/syscalls/syscalls.cpp
- src/plugins/windowmon/windowmon.cpp
- src/plugins/wmimon/wmimon.cpp
This should make _drakvuf_ more accurate.
> Use attached process data

- src/plugins/filetracer/win_acl.cpp
- src/plugins/procdump/procdump.cpp
This are:
* `g_assert`-s in _procdump_
* Buffer allocation error in _filetracer_
> Fix some places leading to SIGABRT

- src/plugins/syscalls/linux.cpp
- src/plugins/syscalls/private.h
- src/plugins/syscalls/syscalls.cpp
- src/plugins/syscalls/win.cpp
:thinking: I need to test it carefully
> syscalls: Additional fix for OUTPUT_JSON

- src/libusermode/userhook.cpp
- src/plugins/socketmon/socketmon.cpp
@tklengyel, I just have found some issue while using `vmi_lock_guard` in plugin initialization.
In _socketmon_ I caught a deadlock in enumerating processes after initializing a `vmi_lock_guard`.
I fixed similar place in _userhook_ too just for sure.
> Fix some possible deadlocks

- src/plugins/procdump/writer.cpp
I forgot to push this little change with _procdump_ branch...
> procdump: replace assert with warning

- package/Dockerfile-xen
- package/depends.sh
- package/mkdeb
A little refactor, now it should be simultaneously compatible with `ubuntu:focal`, `ubuntu:bionic` and `debian:buster`.
> Refactor package build, improve compatibility

- package/Dockerfile-xen
- package/build.sh
- package/depends.sh
- package/swab.patch
* Fix few typos
* Add `swab.h` patch for Debian to make qemu build properly
> Fix typos in package/depends.sh

- .travis.yml
- package/build.sh
> Fix package build

- src/main.cpp
- src/plugins/plugins.cpp
- src/plugins/plugins.h
- src/plugins/syscalls/linux.cpp
- src/plugins/syscalls/syscalls.cpp
- src/plugins/syscalls/syscalls.h
- src/plugins/syscalls/win.cpp
I tried to make disabling sysret functionality very similar to the functionality of disabling other plugins.
> Add possibility of disabling sysret plugin

- src/libinjector/injector_stack.c
- src/libinjector/libinjector.h
- src/libinjector/linux_injector.c
- src/libinjector/private.h
- src/libinjector/win_injector.c
- src/plugins/filedelete/filedelete2_helpers.cpp
- src/plugins/procdump/procdump.cpp
> Don't use SET_REGISTERS event response in injector

- src/libinjector/win_injector.c
> injector: fix register restoring

- src/libinjector/win_injector.c
> injector: fix race condition when TID is not specified

- src/plugins/filetracer/filetracer.cpp
> filetracer: print status of NtCreateFile

- src/libusermode/printers/printers.cpp
- src/libusermode/printers/printers.hpp
> libusermode: add const qualifier to printers

- src/plugins/syscalls/private.h
- src/plugins/syscalls/win.h
> Syscalls new functions

- src/libusermode/printers/printers.cpp
- src/libusermode/printers/printers.hpp
- src/libusermode/userhook.cpp
> libusermode: add 'pulong' type

- src/libusermode/printers/printers.cpp
- src/libusermode/printers/printers.hpp
- src/libusermode/userhook.cpp
> libusermode: add CLSID and IID types to printers

- src/libinjector/win_injector.c
fix bugs which were preventing readfile from working, properly handle when CreateFileW or ReadFile returns FALSE
> injector: fix readfile

- src/libusermode/printers/printers.cpp
- src/libusermode/printers/printers.hpp
- src/libusermode/userhook.cpp
> libusermode: add 'lpvoid*' type

- src/libusermode/printers/printers.cpp
- src/libusermode/printers/printers.hpp
> libusermode: fix WoW64 unicode printing

- src/plugins/syscalls/syscalls.cpp
- src/plugins/syscalls/win.cpp
- src/plugins/syscalls/win.h
> syscalls: print _OBJECT_ATTRIBUTES

- src/plugins/filetracer/win.cpp
This is ongoing work. The Linux part will be in separate PR.
> filetracer: switch to new printing API (windows only)

- src/plugins/procmon/privileges.cpp
- src/plugins/procmon/privileges.h
- src/plugins/procmon/procmon.cpp
> procmon: refactor printing privileges with new printing API

- src/plugins/filedelete/filedelete.cpp
- src/plugins/filedelete/filedelete.h
- src/plugins/filedelete/filedelete2_helpers.cpp
- src/plugins/filedelete/private.h
This allows to dump files opened for asynchronous access
> fileextractor: dump files with sections and views

- src/libdrakvuf/drakvuf.c
- src/libdrakvuf/libdrakvuf.h
- src/libdrakvuf/private.h
- src/libdrakvuf/vmi.c
Provide API in libdrakvuf such that plugins could interact with Intel Processor Trace feature.
> ipt: implement IPT functions in libdrakvuf

- src/plugins/procmon/procmon.cpp
> procmon: fix memory corruption

- package/extra/etc/default/grub.d/xen.cfg
> Check if drakvuf-bundle is installed before applying /etc/default/grub.d/xen.cfg

- src/plugins/procdump/procdump.cpp
> procdump: don't dump process if it not going to terminate

- .github/workflows/cppcheck.yml
- .github/workflows/whitespace.yml
> Add more Github Actions checks

- src/plugins/plugins.cpp
- src/plugins/plugins.h
No functional changes.
cc @BonusPlay @icedevml
> plugins: Use automatic memory management

- package/Dockerfile-final
- package/depends.sh
- package/mkdeb
drakvuf-bundle: start shiping `dwarf2json` tool to `/usr/bin`
> ship dwarf2json with drakvuf-bundle

- src/drakvuf.cpp
- src/libinjector/win_injector.c
Thanks to @disaykin to noticed that.
> Fix logical errors in injected process termination

- src/libusermode/printers/printers.cpp
- src/libusermode/printers/printers.hpp
- src/libusermode/userhook.cpp
~~This is already re-based onto #1073 and #1074~~ I have re-based onto `master` branch to simplify compare
This is a special meta type to dump memory regions.
> libusermode: add binary16 type to dump memory regions

- src/libdrakvuf/linux.c
- src/plugins/procmon/winnt.cpp
- src/plugins/procmon/winnt.h
Analysis Summary:
New defects found: 0
Defects eliminated: 15
> fix: Coverity Scan analysis warnings

- src/exitcodes.h
- src/main.cpp
Add a new return code to indicate an injector error.
> Add INJECTION_ERROR exit code

- src/libdrakvuf/vmi.c
- src/libinjector/linux_injector.c
- src/libinjector/win_injector.c
- src/main.cpp
This is already re-based on #1073 
Current debug messages for different loops are rather confusing.
> Refactor messages

- src/plugins/procdump/private.h
Unfortunately I don't fully understand the underlying structures. Though with this checks I have fixed multiple BSODs.
> procdump: fix MMPTE check for accessible pages

- src/plugins/output_format/ostream.cpp
- src/plugins/syscalls/syscalls.cpp
- src/plugins/syscalls/syscalls.h
On my tests, there is a 5-15% increase in the number of events in the same time.
> Optimize print subsystem

- src/libusermode/printers/printers.cpp
- src/libusermode/printers/printers.hpp
- src/libusermode/userhook.cpp
- src/libusermode/userhook.hpp
- src/plugins/apimon/apimon.cpp
- src/plugins/memdump/userhook.cpp
- src/plugins/rpcmon/rpcmon.cpp
* Extracted `numeric_format` and and `print_no_addr` into a `PrinterConfig` for easier extendability
* Added more error checking
* Reworked parsing code for less duplication
* ~~Added `UserHookException` to handle parsing errors and easier debugging (line number information)~~
> libusermode: Cleanup

- src/plugins/output_format/ostream.cpp
> Don't buffer output when printing to terminal

- src/libhook/hooks/return.cpp
- src/libhook/hooks/return.hpp
- src/libhook/hooks/syscall.hpp
- src/plugins/plugins_ex.h
> fixes to double-free and use-after-free

- src/libhook/hooks/return.hpp
- src/libhook/hooks/syscall.hpp
- src/plugins/plugins_ex.h
closes https://github.com/tklengyel/drakvuf/issues/1188
> Fix uninitialized variables in libhook

- configure.ac
- src/libdrakvuf/drakvuf.c
- src/libdrakvuf/libdrakvuf.h
- src/libdrakvuf/private.h
- src/libdrakvuf/vmi.c
- src/libhook/hooks/return.hpp
- src/libhook/hooks/syscall.hpp
- src/plugins/cpuidmon/cpuidmon.h
- src/plugins/debugmon/debugmon.h
- src/plugins/exploitmon/exploitmon.cpp
- src/plugins/plugins_ex.h
- src/plugins/poolmon/poolmon.h
- src/plugins/ssdtmon/ssdtmon.h
Reverts tklengyel/drakvuf#1197, regressions
> Revert "Add unique trap id to avoid relying on pointers as keys"

- src/plugins/exploitmon/exploitmon.cpp
- src/plugins/exploitmon/exploitmon.h
> exploitmon: fix EX_FAST_REF for x64

- src/plugins/apimon/apimon.cpp
- src/plugins/bsodmon/bsodmon.cpp
- src/plugins/cpuidmon/cpuidmon.cpp
- src/plugins/debugmon/debugmon.cpp
- src/plugins/delaymon/delaymon.cpp
- src/plugins/envmon/envmon.cpp
- src/plugins/filedelete/filedelete.cpp
- src/plugins/filetracer/linux.cpp
- src/plugins/filetracer/win.cpp
- src/plugins/filetracer/win_acl.cpp
- src/plugins/memdump/memdump.cpp
- src/plugins/objmon/objmon.cpp
- src/plugins/poolmon/poolmon.cpp
- src/plugins/windowmon/windowmon.cpp
> refactor plugins: output related codes

- package/extra/etc/default/grub.d/xen.cfg
Update Xen command line to match the one used on GitHub pages.
> package: Update Xen command line

- src/libusermode/userhook.cpp
Unify the use of vmi_lock_guard in libusermode
> Unify use of vmi_lock_guard in libusermode

- src/libusermode/userhook.cpp
Remove user mode hooks on MmCleanProcessAddressSpace call instead of NtTerminateProcess
* Eliminated race condition while terminating multi-threaded applications.
* Fixed case when NtTerminateProcess fails (i.e. with not enough permissions),
and we already removed the hooks from actually non-terminated process.
> Remove user mode hooks on MmCleanProcessAddressSpace

- src/libdrakvuf/drakvuf.c
- src/libdrakvuf/libdrakvuf.h
- src/libdrakvuf/private.h
- src/libdrakvuf/vmi.c
- src/libdrakvuf/vmi.h
Hello! I was surprised there were no MSR traps, so I added them :)
> added msr trap support

- src/helpers/hiddump/hiddump.c
Dear Tamas, 
this PR fixes the issues with the newly added code in `src/helpers/hiddump/hiddump.c`, which were identified by Coverity. The following issues were addressed: 
- control flow issues in L. 246 and 599 (of the previous file version)
- error handling issue in L. 468 previously  
- resource leak issue in  L. 488 previously
I added the report, which was provided by you as an attachment to this PR: [2021-06-14_hiddump-coverity.txt](https://github.com/tklengyel/drakvuf/files/6650421/2021-06-14_hiddump-coverity.txt)
I hope, that these changes solve my blunders!
Thanks for pointing me on them. 
Best regards 
Jan
> Fix issues in hiddump.c identified by coverity

- src/libdrakvuf/linux-processes.c
> use kpgd when accessing task_struct

- src/libinjector/injector_stack.c
- src/libinjector/libinjector.h
adds `init_string_argument` similar to existing `init_int_argument`
> add init_string_argument

- src/exitcodes.h
- src/main.cpp
Add timeout option for write-file injection (default: 0 == no timeout)
> Add --write-file-timeout option

- src/plugins/envmon/envmon.cpp
- src/plugins/filedelete/filedelete.cpp
- src/plugins/filetracer/win.cpp
> Fix KV output format

- src/drakvuf.cpp
- src/plugins/exploitmon/exploitmon.cpp
- src/plugins/exploitmon/exploitmon.h
Hello! I've added final analysis in exploitmon. With this update we will be able to monitor token modification in every process.
Thanks!
> Exploitmon update

- src/plugins/procmon/procmon.cpp
**Why we want to log MmCleanProcessAddressSpace**
`NtTerminateProcess` is not always called when process is terminating. 
**If MmCleanProcessAddressSpace is better for tracking, then why we want to log `NtTerminateProcess` anyway**
`NtTerminateProcess` provides more details than `MmCleanProcessAddressSpace` such as process `ExitCode`.
> Log MmCleanProcessAddressSpace

- src/libinjector/injector_stack.c
Reference: https://blog.rchapman.org/posts/Linux_System_Call_Table_for_x86_64/
> [Linux] modify setup_stack for updated injector

- src/libinjector/injector.c
- src/libinjector/linux/linux_injector.c
- src/libinjector/linux/linux_utils.h
- src/libinjector/private.h
This is a prerequisite for writefile and readfile methods
> [Linux] change signature of injector_start_app_on_linux

- src/libinjector/Makefile.am
- src/libinjector/linux/linux_injector.c
- src/libinjector/linux/linux_syscalls.c
- src/libinjector/linux/linux_syscalls.h
- src/libinjector/linux/methods/linux_read_file.c
- src/libinjector/linux/methods/linux_read_file.h
This PR adds `readfile` method to linux injector
> [Linux] add readfile method

- .github/workflows/compile.yml
Update compile.yml to use matrix for simultaneous builds and improved caching
> [ci] simultaneously compile the builds and improve caching

- src/libinjector/linux/linux_syscalls.c
- src/libinjector/linux/linux_syscalls.h
- src/libinjector/linux/linux_utils.c
- src/libinjector/linux/linux_utils.h
- src/libinjector/linux/methods/linux_read_file.c
- src/libinjector/linux/methods/linux_shellcode.c
- src/libinjector/linux/methods/linux_write_file.c
This PR consists of refactoring changes for the new Linux injector.
> [Linux] refactor injector

- src/libinjector/injector_stack.c
I have tried to add `PRINT_DEBUG` statements throughout `injector_stack`. Please let me know if I have to remove or add some debug statements anywhere
> add print_debug statements in injector_stack

- src/libusermode/running.cpp
@BonusPlay Please review my change, it seems like I'm right, in any case, I did not find any differences in the code and behavior.
> Replace get_func_addr implementation by vmi_translate_sym2v

- src/plugins/procmon/procmon.cpp
Previous implementation:
- does not work on x86 arch (uses incorrest offset for _UNICODE_STRING->Buffer)
- does not convert UTF-16 to UTF-8 (copies only non-zero bytes instead)
> Fix incorrect support for long CommandLine strings in procmon plugin

- src/main.cpp
- src/plugins/plugins.cpp
- src/plugins/ssdtmon/private.h
- src/plugins/ssdtmon/ssdtmon.cpp
- src/plugins/ssdtmon/ssdtmon.h
Added SSDT Shadow support for `ssdtmon` plugin.
> ssdtmon ssdt shadow update

- src/libinjector/Makefile.am
- src/libinjector/win/methods/win_createproc.c
- src/libinjector/win/methods/win_createproc.h
- src/libinjector/win/methods/win_read_file.c
- src/libinjector/win/methods/win_write_file.c
- src/libinjector/win/win_injector.c
- src/libinjector/win/win_utils.h
Related https://github.com/tklengyel/drakvuf/issues/936
Although, this method was split across x86 and x64 `if` paths separately, but they seemed similar only to me so I've combined them. Let me know if you think that is a mistake
> win_injector: seperate createprocess method

- src/libinjector/Makefile.am
- src/libinjector/win/methods/win_shellexec.c
- src/libinjector/win/methods/win_shellexec.h
- src/libinjector/win/win_injector.c
> win_injector: seperate shellexec method

- src/libinjector/win/win_utils.c
From https://github.com/tklengyel/drakvuf/pull/1257
> libinjector: fix empty process name. Fix #1339

- .github/workflows/ci.yml
- configure.ac
Check doppelganging compilations and fix help string
> ci: check doppelganging injection compilation

- src/libinjector/win/methods/win_write_file.c
- src/libinjector/win/methods/win_write_file.h
- src/libinjector/win/win_injector.c
Add x86 writefile support, tested on win7x86
> libinjector: add x86 writefile support

- src/injector.c
- src/libinjector/Makefile.am
- src/libinjector/private.h
- src/libinjector/win/methods/win_dopple.c
- src/libinjector/win/methods/win_shellcode.c
- src/libinjector/win/methods/win_shellcode.h
- src/libinjector/win/win_injector.c
- src/libinjector/win/win_utils.c
I had actually refactored doppelganging method also here, I'll open up a new PR to remove all the instances of it
Related https://github.com/tklengyel/drakvuf/issues/936
> win_injector: seperate shellcode method

- src/main.cpp
- src/plugins/plugins.cpp
- src/plugins/plugins.h
- src/plugins/procdump2/README.md
- src/plugins/procdump2/private2.h
- src/plugins/procdump2/procdump2.cpp
- src/plugins/procdump2/procdump2.h
* Fix issue with not self-terminating processes
* Add other injection path for KeDelayExecutionThread
* Add arguments to simplify path check
> procdump2: big re-factoring

- src/drakvuf.h
- src/libinjector/Makefile.am
- src/libinjector/win/methods/win_terminate.c
- src/libinjector/win/methods/win_terminate.h
- src/libinjector/win/win_injector.c
- src/libinjector/win/win_utils.h
Closes https://github.com/tklengyel/drakvuf/issues/936
> win_injector: seperate terminate method

- src/libusermode/printers/printers.cpp
- src/plugins/output_format/kvfmt.h
There have been noticed multiple errors in `apimon` and `regmon` output with multi-line strings and strings with quotes and other symbols. E.g.:
```
regmon Time=1646227127.515052,PID=5604,PPID=624,TID=1972,ProcessName="\Device\HarddiskVolume2\Windows\System32\svchost.exe",Method=NtSetValueKey,Key="\REGISTRY\MACHINE\SYSTEM\SYSTEM\WAAS\WAASMEDIC\TASKSTORE",ValueName="Schedule Scan",Value="'Microsoft\Windows\UpdateOrchestrator','<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.6" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
<RegistrationInfo>
<Source>Microsoft Corporation</Source>
<Author>Microsoft Corporation</Author>
<Version>1.0</Version>
<Description>This task performs a scheduled Windows Update scan.</Description> …
```
> Fix string escaping with library function g_strescape

- src/plugins/plugins_ex.h
> Fix UB from issue #1395 in plugins_ex part of libhook

- src/plugins/procdump2/private2.h
- src/plugins/procdump2/procdump2.cpp
Fix logical errors:
* On "host"-process becomes target one.
* On task timeout state switch.
Both errors result in BSODs.
> procdump2: fix logical errors resulting in BSODs

- src/plugins/procmon/linux.cpp
Print initial process list in `procmon` for Linux.
Relates to https://github.com/tklengyel/drakvuf/pull/1458
> procmon: print initial process list for linux

- src/drakvuf.cpp
- src/drakvuf.h
- src/injector.c
- src/libdrakvuf/drakvuf.c
- src/libdrakvuf/libdrakvuf.h
- src/libdrakvuf/private.h
- src/libdrakvuf/vmi.c
- src/main.cpp
- src/proc_stat.cpp
- src/repl.cpp
- src/xtf.c
Add possibility to exclude some processes from monitoring
> add possibility to ignore events from specified processes

- src/libdrakvuf/win-processes.c
This allows to avoid unnecessary `vmi_read_str_va / g_free`
> Refactor Windows process name retrival

- configure.ac
- src/libdrakvuf/drakvuf.c
- src/libdrakvuf/libdrakvuf.h
- src/libdrakvuf/vmi.c
- src/libinjector/injector_stack.c
- src/libinjector/libinjector.h
- src/libusermode/Makefile.am
- src/libusermode/running.cpp
- src/libusermode/userhook.cpp
- src/libusermode/userhook_inject.cpp
This is a missed part of #1450 
I have tried to split my work to several PRs. This result in errors like this.
> Libusermode fix

- configure.ac
- meson_options.txt
- src/plugins/Makefile.am
- src/plugins/ebpfmon/ebpfmon.cpp
- src/plugins/ebpfmon/ebpfmon.h
- src/plugins/ebpfmon/private.h
- src/plugins/meson.build
- src/plugins/plugins.cpp
- src/plugins/plugins.h
Added a plugin to track eBPF (also bpf) calls to the kernel.
> linux: new plugin ebpfmon

- src/plugins/filetracer/filetracer.cpp
- src/plugins/filetracer/filetracer.h
- src/plugins/filetracer/linux.cpp
- src/plugins/filetracer/linux.h
- src/plugins/filetracer/private.h
- src/plugins/procmon/linux.h
- src/plugins/rootkitmon/private.h
- src/plugins/rootkitmon/rootkitmon.cpp
- src/plugins/rootkitmon/rootkitmon.h
Hi, I decided to refactor the plugin for a more C++ style, like others Linux plugins.
Also fixed the following functions that were commented out:
```bash
__x64_sys_memfd_create
utimes_common
do_faccessat
vfs_readlink
```
> linux-filetracer: Refactor plugin

- src/libdrakvuf/linux-processes.c
- src/libinjector/debug_helpers.c
- src/libinjector/linux/linux_injector.c
- src/libinjector/linux/linux_syscalls.c
- src/libinjector/linux/linux_utils.h
- src/libinjector/linux/methods/linux_execve.c
This fixes multiple errors which result in "write file timeout" and "Failed to get TID"
> Fix libinjector linux support

- src/libdrakvuf/drakvuf.c
- src/libdrakvuf/libdrakvuf.h
- src/main.cpp
- src/plugins/bsodmon/bsodmon.cpp
- src/plugins/bsodmon/bsodmon.h
- src/plugins/plugins.cpp
- src/plugins/plugins.h
> bsodmon: store full memory dump on kernel panic

- src/libinjector/injector_stack.c
- src/libinjector/libinjector.h
- src/libusermode/running.cpp
- src/libusermode/uh-private.hpp
- src/libusermode/userhook_inject.cpp
This allows to check some errors while injections
> libinjector: add stack marker

- src/plugins/procdump2/private2.h
- src/plugins/procdump2/procdump2.cpp
- src/plugins/procdump2/procdump2.h
Several logical errors been fixed
> libinjector: fix procdump2 for BSODs

- src/main.cpp
> Put plugin specific variable in ifdef

- src/plugins/Makefile.am
- src/plugins/helpers/hooks.h
- src/plugins/helpers/type_traits.h
- src/plugins/helpers/unicode_string.h
- src/plugins/helpers/vmi_lock_guard.h
- src/plugins/output_format/common.h
- src/plugins/output_format/csvfmt.h
- src/plugins/output_format/deffmt.h
- src/plugins/output_format/jsonfmt.h
- src/plugins/output_format/kvfmt.h
- src/plugins/plugins.h
- src/plugins/plugins_ex.h
- src/plugins/procmon/linux.cpp
Haven't got time to test it myself, so I'm using CI tests.
> Add unicode_string helper

- src/plugins/output_format/csvfmt.h
- src/plugins/output_format/deffmt.h
- src/plugins/output_format/jsonfmt.h
- src/plugins/output_format/kvfmt.h
- src/plugins/output_format/xfmt.h
> Add more const arguments to output_format

- src/libdrakvuf/vmi.c
It had been noticed that if injection occur (`RIP` changed) then there is no need to single-step the `INT3` trap.
This optimization lead to 10-20% speedup in my tests.
> libdrakvuf: skip single-step on injection for spead

- src/plugins/syscalls/linux.cpp
> syscalls: add messages on plug-in constructor fail

- configure.ac
- meson_options.txt
- src/main.cpp
- src/plugins/Makefile.am
- src/plugins/linkmon/linkmon.cpp
- src/plugins/linkmon/linkmon.h
- src/plugins/linkmon/private.h
- src/plugins/meson.build
- src/plugins/plugins.cpp
- src/plugins/plugins.h
Plugin extracts and prints information from:
- Hard links
- Junction points
- Symbolic links
Plugin uses offsets from `ole32.dll`.
> linkmon: new plugin for getting information from NTFS links

- src/libhook/Makefile.am
- src/libhook/call_result.hpp
- src/libhook/hooks/memaccess.cpp
- src/libhook/hooks/memaccess.hpp
- src/libhook/meson.build
- src/plugins/codemon/codemon.cpp
- src/plugins/codemon/codemon.h
- src/plugins/codemon/private.h
- src/plugins/plugins.cpp
- src/plugins/plugins_ex.h
Refactor big part of codemon. Migrate traps to RAII managed hooks, implement page faulting for vmi_extended_lookups and more fixups. Not everything is yet ported, but it's a start.
This is a "RFC" PR, I want to finish running local tests before merge.
> Codemon refactor

- src/plugins/fileextractor/fileextractor.cpp
Small fix for algorithm logic:
First `NtWriteFile` was not handled properly for files opened with `FILE_APPEND_DATA` flag
> fileextractor fix logic

- src/main.cpp
- src/plugins/filetracer/filetracer.cpp
- src/plugins/filetracer/filetracer.h
- src/plugins/filetracer/private.h
- src/plugins/filetracer/win.cpp
- src/plugins/filetracer/win.h
- src/plugins/plugins.cpp
Hello, I refactored windows part of filetracer
> filetracer refactoring

- src/plugins/unixsocketmon/unixsocketmon.cpp
Some byte sequences may pass `vmi_convert_str_encoding` check and be shown as Unicode string by mistake. Ths leads to strings like `"\u0001\u0002..."`  in output.
There is additional filter that checks byte arrays for non-printable characters, and that trailing zeroes only appears at the end of byte sequence.
> unixsocketmon: add filter for printable strings

- src/plugins/procdump2/procdump2.cpp
fix memory leak of process_name if process is in exclude list
> procdump2: proc_name memory leak fix

- src/plugins/regmon/regmon.cpp
- src/plugins/regmon/regmon.h
Hello I slightly refactored regmon and add registry create/open options to get whether registry symlink created/opened - `REG_OPTION_CREATE_LINK` and `REG_OPTION_OPEN_LINK`.
P.S.
`REG_OPTION_NON_VOLATILE` is ignored because it's not useful
> regmon modification and refactoring

- src/plugins/filetracer/private.h
- src/plugins/filetracer/win.cpp
- src/plugins/filetracer/win.h
> Partially revert PR #1661

- src/plugins/fileextractor/fileextractor.cpp
size check was replaced with try/catch
> use try catch in fileextractor 

- src/libusermode/uh-private.hpp
- src/libusermode/userhook.cpp
- src/libusermode/userhook_inject.cpp
- src/libusermode/userhook_pf.cpp
* remove usage of inner trap on MmCopyVirtualMemory
* fix some subtle bugs in ntdll hooking
> libusermode: fix subtle bugs and simplify userhook_injector code

- src/libinjector/linux/linux_injector.c
> fix error message for do_exit trap in linux_injector

- src/libdrakvuf/drakvuf.c
- src/libdrakvuf/libdrakvuf.h
- src/libdrakvuf/private.h
- src/libdrakvuf/win-processes.c
- src/plugins/output_format/csvfmt.h
- src/plugins/output_format/jsonfmt.h
- src/plugins/output_format/kvfmt.h
- src/plugins/procmon/private.h
- src/plugins/procmon/win.cpp
- src/plugins/procmon/win.h
- src/plugins/syscalls/win.cpp
- src/plugins/syscalls/win.h
This fields are used to detect heaven's gate technique
> add Bitness and FromParentModule field

- src/plugins/socketmon/socketmon.cpp
- src/plugins/socketmon/socketmon.h
Hello. The UDP hook had remote and local targets switched. This pr fixes the issue plus adds real local ip and local port. Unfortunately the offsets are undocumented so I hardcoded whem.
> fix udp src & dst targets

- src/plugins/procdump2/win.cpp
- src/plugins/procdump2/win.h
- src/plugins/procdump2/win_minidump.h
- src/plugins/procdump2/win_private.h
Lot's of hard to debug BSODs fixed.
Based on and requires: https://github.com/tklengyel/drakvuf/pull/1777
> procdump2: fix many BSODs due to logical errors

- src/plugins/fileextractor/fileextractor.cpp
- src/plugins/fileextractor/fileextractor.h
- src/plugins/fileextractor/private.h
Based on https://github.com/tklengyel/drakvuf/pull/1779
> fileextractor: log stage switches and other events

- src/plugins/fileextractor/private.h
- src/plugins/fileextractor/win.cpp
Hi, I fixed some bugs that could cause files to not be extracted correctly
> fileextractor: fix some bugs

- .github/workflows/ci.yml
Another attempt to enable **check** in CI.
> run "make check" as a separate stage in CI
